# Site settings
title: "The Budget AI Lab"
tagline: "Нейросети на P102-100: Экстремальный тюнинг Xeon & GPU"
description: "Лаборатория по выжиму максимума из дешевого серверного железа для задач Deep Learning и ИИ."
url: 'https://lybra-ai.ru'
github:
  username: lybra-bee

# Настройки оформления
theme_mode: dark # Всегда темная тема для стиля "Lab"
avatar: 'https://raw.githubusercontent.com/cotes2020/chirpy-images/main/commons/devices-mockup.png' # Потом замените на фото своего ПК

# Соцсети (оставьте только нужные)
social:
  name: "Admin"
  email: "all77home@list.ru"
  links:
    - https://github.com/lybra-bee
    - https://t.me/lybra777

# Важные технические настройки для GitHub Pages
baseurl: "" # Оставьте пустым, если репозиторий называется ваш-ник.github.io
timezone: Europe/Moscow
lang: ru-RU

# Пагинация и поиск
google_analytics:
  id: '' # Сюда потом вставите ID для аналитики
