# Site settings
title: "Lybra AI Lab"
tagline: "Нейросети на P102-100: Экстремальный тюнинг Xeon & GPU"
description: "Лаборатория по выжиму максимума из бюджетного железа для задач Deep Learning."

# Настройки домена (КРИТИЧНО ДЛЯ ВАШЕГО СЛУЧАЯ)
url: "https://lybra-ai.ru"
baseurl: "" # ОСТАВИТЬ ПУСТЫМ! Не ставьте даже слэш "/"

# Настройки GitHub
github:
  username: lybra-bee
  repository: lybra-bee.github.io

# Тема и плагины
theme: jekyll-theme-chirpy
lang: ru-RU
timezone: Europe/Moscow

# Оформление
theme_mode: dark # Чтобы сразу был красивый темный интерфейс

# Пагинация
paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
