baseURL = "https://lybra-bee.github.io/"
languageCode = "ru-ru"
title = "AI Портфолио"

[params]
description = "Портфолио сгенерированных AI статей и изображений"

[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Статьи"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    name = "Галерея"
    url = "/gallery/"
    weight = 3

  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 4

[outputs]
  home = ["HTML", "RSS"]
