baseURL = "https://lybra-bee.github.io/"
languageCode = "ru-RU"
title = "Lybra Bee - Портфолио и Блог об ИИ"
theme = "toha"

[params]
  background = "/images/design/site-background.jpg"  # Замени на своё нагенерированное изображение (AI-нейрон, 1920x1080)
  enableBlogPost = true
  enableTOC = true
  darkMode.enable = true
  features.pwa.enabled = true
  features.search.enabled = true
  gitRepo = "https://github.com/lybra-bee/lybra-bee.github.io"

[params.logo]
  main = "/images/design/logo.png"  # Замени на своё (200x200, AI-иконка)

[params.features.portfolio.sections]
  name = "Галерея"
  weight = 3

[menu]
  [[menu.main]]
    name = "Все статьи"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Галерея"
    url = "/gallery/"
    weight = 2
  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 3
    [module]
  [[module.mounts]]
    source = "themes/toha @ abeb605/node_modules"
    target = "assets/node_modules"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
