baseURL = "https://USERNAME.github.io/REPO_NAME/"
languageCode = "ru"
title = "Мой AI-блог"
theme = "ananke"

[params]
  author = "Алексей"
  description = "Блог о нейросетях, генерации видео и современных технологиях."
