baseURL = "https://lybra-bee.github.io/"
languageCode = "ru"
title = "Alexey AI"

# Меню
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Статьи"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "gallery"
    name = "Галерея"
    url = "/gallery/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = 4
