baseURL = "https://lybra-bee.github.io/"
languageCode = "ru-ru"
title = "Alexey AI"
theme = "ananke"
enableRobotsTXT = true
hasCJKLanguage = false
defaultContentLanguage = "ru"
pygmentsUseClasses = true
theme = "ananke"

[pagination]
  pagerSize = 10

# Вывод
[outputs]
  home = ["HTML"]

# Меню
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Статьи"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "gallery"
    name = "Галерея"
    url = "/gallery/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "Обо мне"
    url = "/about/"
    weight = 4

# Параметры сайта
[params]
  description = "Блог о генеративных нейросетях, ИИ и технологиях"
  author = "Alexey"
  showReadMore = true
  showLastModified = true

# Социальные ссылки
[social]
  github = "https://github.com/lybra-bee"
  telegram = "https://t.me/Lybra777"
