FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_bot.txt .
RUN pip3 install --no-cache-dir -r requirements_bot.txt

COPY scripts/telegram_bot.py .

CMD ["python3", "telegram_bot.py"]
