baseURL = 'https://lybra-bee.github.io/'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru'
title = 'AI Blog - Генерация контента ИИ'
# theme = 'hugo-theme-stack'  # ЗАКОММЕНТИРОВАТЬ или УДАЛИТЬ эту строку!

[params]
  subtitle = "Самые свежие статьи и тренды AI 2025"
  primaryColor = "#2563eb"
  backgroundColor = "#0f172a"
  textColor = "#f8fafc"

[author]
  name = "Lybra-Bee"

[languages]
  [languages.ru]
    weight = 1
    languageName = "Русский"

[menu]
[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Статьи" 
url = "/posts/"
weight = 2

[[menu.main]]
name = "Архив"
url = "/archive/"
weight = 3

[outputs]
home = ["HTML", "RSS"]
