baseURL = "https://lybra-bee.github.io/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "AI Blog - Генерация контента ИИ"

[params]
  subtitle = "Самые свежие статьи и тренды AI 2025"
  primaryColor = "#2563eb"
  backgroundColor = "#0f172a"
  textColor = "#f8fafc"

[author]
  name = "Lybra-Bee"

[menu]
[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Статьи"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Архив"
url = "/archive/"
weight = 3

[outputs]
home = ["HTML", "RSS"]
