baseURL = 'https://lybra-bee.github.io/'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru'
title = 'AI Blog - Генерация контента ИИ'
theme = ''

# Параметры сайта
[params]
  description = 'Автоматически генерируемый блог об искусственном интеллекте и технологиях 2025 года'
  primaryColor = '#2563eb'
  backgroundColor = '#0f172a'
  textColor = '#f8fafc'
  subtitle = 'Самые свежие статьи и тренды AI 2025'
  recent_posts_number = 3
  show_reading_time = true
  show_word_count = true
  custom_css = ["css/custom.css"]
  mainSections = ["posts"]
  background_image = "/assets/images/design/hero-bg.jpg"
  primary_color = "#0af"
  secondary_color = "#08c"
  github_url = "https://github.com/lybra-bee"
  email = "your.email@example.com"
  font_family = "Segoe UI, Tahoma, Geneva, Verdana, sans-serif"
  font_size = "16px"
  line_height = "1.6"
  accent_color = "#0af"
  card_background = "rgba(15, 23, 42, 0.6)"
  enable_animations = true
  enable_particles = true
  generator = "Hugo + AI Content"
  keywords = "ai, искусственный интеллект, машинное обучение, 2025"
  custom_js = ["js/main.js"]
  default_image = "/assets/images/default.png"
  hero_image = "/assets/images/design/hero-bg.jpg"
  posts_per_page = 10
  show_featured_image = true
  show_author = false
  show_date = true
  show_read_time = true

# Настройки автора
[author]
  name = 'Lybra-Bee'

# Языковые настройки
[languages]
  [languages.ru]
    languageName = 'Русский'
    weight = 1
    title = 'AI Blog - Генерация контента ИИ'
    [languages.ru.params]
      description = 'Автоматически генерируемый блог об искусственном интеллекте и технологиях 2025 года'

# Настройки меню
[menu]
  [[menu.main]]
    name = 'Главная'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'Статьи'
    url = '/posts/'
    weight = 2

  [[menu.main]]
    name = 'Галерея'
    url = '/gallery/'
    weight = 3

  [[menu.main]]
    name = 'Обо мне'
    url = '/about/'
    weight = 4

# Настройки сборки
[build]
  writeStats = true
  buildFuture = true
  buildExpired = true
  noChmod = true
  noTimes = true
  minifyHTML = true
  minifyCSS = true
  minifyJS = true
  compressCSS = true
  compressJS = true
  cacheBuster = true
  enableGitInfo = true
  enableEmoji = true
  enableRobotsTXT = true
  disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Настройки модулей
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'content'
    target = 'content'

  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'

# Настройки обработки изображений
[imaging]
  quality = 85
  resampleFilter = 'Lanczos'
  anchor = 'center'
  bgColor = '#ffffff'
  [imaging.exif]
    excludeFields = ".*"
    includeFields = "^Make$|^Model$|^Orientation$|^GPS*"

# Настройки Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
      xHTML = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    codeFences = true
    guessSyntax = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Настройки налоговомий
[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

# Настройки социальных сетей
[social]
  GitHub = 'https://github.com/lybra-bee'

# Настройки sitemap
[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

# Настройки RSS
[services]
  [services.rss]
    limit = 20
    disable = true

# Настройки безопасности
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^python$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GITHUB_']
  [security.http]
    methods = ['GET', 'POST']

# Настройки обработки данных
[data]
  [data.config]
    kind = 'yaml'

# Настройки обработки контента
[content]
  [content.frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    lastmod = ['lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
    expiryDate = ['expiryDate']

# Настройки обработки URL
[permalinks]
  posts = '/posts/:year/:month/:title/'
  pages = '/:slug/'
  tags = ""
  categories = ""

# Настройки обработки времени
[time]
  location = 'Europe/Moscow'

# Настройки обработки ошибок
[error]
  404 = '/404.html'

# Настройки обработки минификации
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

# Настройки обработки ресурсов
[asset]
  [asset.postcss]
    noMap = true

# Настройки обработки метаданных
[meta]
  [meta.openGraph]
    title = 'AI Blog - Генерация контента ИИ'
    description = 'Автоматически генерируемый блог об искусственном интеллекте и технологиях 2025 года'
    siteName = 'AI Blog'

# Настройки обработки PWA
[pwa]
  manifest = 'manifest.json'
  themeColor = '#2563eb'
  backgroundColor = '#0f172a'

# Настройки обработка кастомных output
[outputs]
  home = ['HTML']
  page = ['HTML']
  section = ['HTML']
  taxonomy = []
  term = []

# Отключение ненужных налоговомий
[disabledKinds]
  taxonomy = true
  taxonomyTerm = true

# Настройки кэширования
[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = -1
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = -1
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = -1

# Настройки для robots.txt
[robotsTXT]
  userAgent = "*"
  allow = ["/"]
  disallow = ["/admin/", "/private/"]
  sitemap = "/sitemap.xml"

# Настройки для кастомных headers
[headers]
  [[headers.for]]
    pattern = "**.css"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
  [[headers.for]]
    pattern = "**.js"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
  [[headers.for]]
    pattern = "**.png"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
  [[headers.for]]
    pattern = "**.jpg"
    [headers.values]
      Cache-Control = "public, max-age=31536000"

# Настройки для кастомных shortcodes
[shortcodes]
  [shortcodes.gallery]
    enable = true
  [shortcodes.accordion]
    enable = true

# Media types
[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]
  [mediaTypes."image/svg+xml"]
    suffixes = ["svg"]

# Output formats
[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isPlainText = false
    isHTML = true

# Deployment (для GitHub Pages)
[deployment]
  [[deployment.targets]]
    name = "github-pages"
    URL = "https://github.com/lybra-bee/lybra-bee.github.io.git"
    branch = "gh-pages"
