baseURL = 'https://lybra-bee.github.io/'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru'
title = 'AI Blog - Генерация контента ИИ'
theme = ''

# Параметры сайта
[params]
  description = 'Автоматически генерируемый блог об искусственном интеллекте и технологиях 2025 года'
  primaryColor = '#2563eb'
  backgroundColor = '#0f172a'
  textColor = '#f8fafc'
  subtitle = 'Самые свежие статьи и тренды AI 2025'
  recent_posts_number = 3
  show_reading_time = true
  show_word_count = true
  custom_css = ["css/custom.css"]
  mainSections = ["posts"]
  background_image = "/assets/images/design/hero-bg.jpg"
  primary_color = "#0af"
  secondary_color = "#08c"

# Настройки автора
[author]
  name = 'Lybra-Bee'

# Языковые настройки
[languages]
  [languages.ru]
    languageName = 'Русский'
    weight = 1
    title = 'AI Blog - Генерация контента ИИ'
    [languages.ru.params]
      description = 'Автоматически генерируемый блог об искусственном интеллекте и технологиях 2025 года'

# Настройки меню
[menu]
  [[menu.main]]
    name = 'Главная'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'Статьи'
    url = '/posts/'
    weight = 2

  [[menu.main]]
    name = 'Галерея'
    url = '/gallery/'
    weight = 3

  [[menu.main]]
    name = 'Обо мне'
    url = '/about/'
    weight = 4

# Настройки сборки
[build]
  writeStats = true
  buildFuture = true
  buildExpired = true
  noChmod = true
  noTimes = true

# Настройки модулей
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'content'
    target = 'content'

  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'

# Настройки обработки изображений
[imaging]
  quality = 85
  resampleFilter = 'Lanczos'
  anchor = 'center'

# Настройки Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true

# Настройки налоговомий
[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

# Настройки социальных сетей
[social]
  GitHub = 'https://github.com/lybra-bee'

# Настройки sitemap
[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

# Настройки RSS
[services]
  [services.rss]
    limit = 20

# Настройки безопасности
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^python$']

# Настройки обработки данных
[data]
  [data.config]
    kind = 'yaml'

# Настройки обработки контента
[content]
  [content.frontmatter]
    date = ['date', 'publishDate', 'lastmod']

# Настройки обработки URL
[permalinks]
  posts = '/posts/:year/:month/:title/'
  pages = '/:slug/'
  tags = '/tags/:slug/'
  categories = '/categories/:slug/'

# Настройки обработки времени
[time]
  location = 'Europe/Moscow'

# Настройки обработки ошибок
[error]
  404 = '/404.html'

# Настройки обработки минификации
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

# Настройки обработки ресурсов
[asset]
  [asset.postcss]
    noMap = true

# Настройки обработки метаданных
[meta]
  [meta.openGraph]
    title = 'AI Blog - Генерация контента ИИ'
    description = 'Автоматически генерируемый блог об искусственном интеллекте и технологиях 2025 года'
    siteName = 'AI Blog'

# Настройки обработки PWA
[pwa]
  manifest = 'manifest.json'
  themeColor = '#2563eb'
  backgroundColor = '#0f172a'

# Настройки обработка кастомных output
[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']

# Отключение ненужных налоговомий (архив и теги)
[disabledKinds]
  # Отключаем страницы тегов
  taxonomy = true
  taxonomyTerm = true
  
  # Отключаем RSS если не нужен
  # RSS = true
  
  # Отключаем секции если не нужны
  # section = true

# Настройки для отключения генерации ненужных страниц
[permalinks]
  # Отключаем генерацию страниц тегов
  tags = ""
  categories = ""
  
  # Оставляем только посты и страницы
  posts = "/posts/:title/"
  pages = "/:slug/"

# Настройки для кастомных output (только HTML)
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  
  # Отключаем генерацию taxonomy
  taxonomy = []
  term = []

# Настройки для отключения ненужных функций
[services]
  [services.rss]
    disable = true  # Отключаем RSS если не нужен

# Настройки для упрощенной сборки
[build]
  # Отключаем ненужные виды страниц
  disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
  
  # Включаем только нужные
  # enableKinds = ["page", "home", "section"]
  
  # Оптимизации сборки
  noChmod = true
  noTimes = true
  buildFuture = true
  buildExpired = true

# Настройки для кастомных layout
[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isPlainText = false
    isHTML = true

# Настройки для обработки изображений (оптимизация)
[imaging]
  resampleFilter = "Lanczos"
  quality = 85
  anchor = "center"
  bgColor = "#ffffff"
  
  [imaging.exif]
    excludeFields = ".*"
    includeFields = "^Make$|^Model$|^Orientation$|^GPS*"

# Настройки безопасности (дополнительные)
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GITHUB_']
  
  [security.http]
    methods = ['GET', 'POST']

# Настройки кэширования
[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = -1
  
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = -1
  
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = -1

# Настройки для кастомных shortcodes (если будут нужны)
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    
    [markup.goldmark.renderer]
      hardWraps = false
      xHTML = false
      unsafe = true
  
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
  
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Настройки для кастомных параметров
[params]
  # Социальные сети
  github_url = "https://github.com/lybra-bee"
  
  # Контакты
  email = "your.email@example.com"
  
  # Настройки оформления
  font_family = "Segoe UI, Tahoma, Geneva, Verdana, sans-serif"
  font_size = "16px"
  line_height = "1.6"
  
  # Настройки цветов
  accent_color = "#0af"
  secondary_color = "#08c"
  text_color = "#f8fafc"
  background_color = "#0f172a"
  card_background = "rgba(15, 23, 42, 0.6)"
  
  # Настройки анимаций
  enable_animations = true
  enable_particles = true
  
  # Настройки мета-информации
  generator = "Hugo + AI Content"
  keywords = "ai, искусственный интеллект, машинное обучение, 2025"
  
  # Настройки для кастомного CSS/JS
  custom_js = ["js/main.js"]
  custom_css = ["css/custom.css"]
  
  # Настройки для изображений
  default_image = "/assets/images/default.png"
  hero_image = "/assets/images/design/hero-bg.jpg"
  
  # Настройки для постов
  posts_per_page = 10
  show_featured_image = true
  show_author = false
  show_date = true
  show_read_time = true

# Настройки для кастомных shortcodes (пример)
[shortcodes]
  [shortcodes.gallery]
    enable = true
  
  [shortcodes.accordion]
    enable = true

# Настройки для кастомных output formats (если понадобятся)
[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]
  
  [mediaTypes."image/svg+xml"]
    suffixes = ["svg"]

# Финальные настройки для production
[deployment]
  # Эти настройки могут быть пустыми, так как деплой через GitHub Actions
  [[deployment.targets]]
    name = "github-pages"
    URL = "https://github.com/lybra-bee/lybra-bee.github.io.git"
    branch = "gh-pages"

# Отключаем ненужные функции для production
[build]
  # Минификация HTML
  minifyHTML = true
  
  # Минификация CSS
  minifyCSS = true
  
  # Минификация JS
  minifyJS = true
  
  # Сжатие ресурсов
  compressCSS = true
  compressJS = true
  
  # Кэширование
  cacheBuster = true
  
  # Оптимизации
  enableGitInfo = true
  enableEmoji = true
  enableRobotsTXT = true

# Настройки для robots.txt
[robotsTXT]
  userAgent = "*"
  allow = ["/"]
  disallow = ["/admin/", "/private/"]
  sitemap = "/sitemap.xml"

# Настройки для кастомных redirects (если понадобятся)
[redirects]
  [[redirects.from]]
    path = "/old-url/"
    to = "/new-url/"
    status = 301

# Настройки для кастомных headers (если понадобятся)
[headers]
  [[headers.for]]
    pattern = "**.css"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
  
  [[headers.for]]
    pattern = "**.js"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
  
  [[headers.for]]
    pattern = "**.png"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
  
  [[headers.for]]
    pattern = "**.jpg"
    [headers.values]
      Cache-Control = "public, max-age=31536000"

# Финальные настройки
[build]
  # Включаем только нужные виды страниц
  disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
  
  # Или явно включаем только нужные
  # enableKinds = ["page", "home"]
  
  # Оптимизации
  writeStats = false
  verbose = false
  quiet = true
  forceSyncStatic = true
  enableMissingTranslationPlaceholders = false

# Настройки для кастомных модулей (если понадобятся)
[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-modules/modules/my-module"
    disable = false

# Резервные настройки
[params.backup]
  enable_backup = false
  backup_dir = "/tmp/backup"
  backup_interval = "24h"
