baseURL = 'https://lybra-bee.github.io/'
languageCode = 'ru-ru'
title = 'Блог и Портфолио Alexey-New'
theme = 'hugo-theme-stack'

[params]
  subtitle = "Программирование и веб-дизайн"
  defaultTheme = "auto"

[author]
  name = "Alexey-New"

[languages]
  [languages.ru]
    weight = 1
    languageName = "Русский"
    title = "Блог и Портфолио"
