baseURL = 'https://lybra-bee.github.io/'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru'
title = 'Блог и Портфолио Alexey-New'
theme = 'hugo-theme-stack'

[params]
  subtitle = "Программирование и веб-дизайн"
  defaultTheme = "auto"
  primaryColor = "#2563eb"
  backgroundColor = "#0f172a"

[author]
  name = "Alexey-New"

[languages]
  [languages.ru]
    weight = 1
    languageName = "Русский"

[params.widgets]
  # Какие виджеты показывать на главной
  home = ["search", "recent"]
  # Какие виджеты показывать в статьях  
  single = ["search", "recent", "categories"]

[menu]
[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Статьи" 
url = "/posts/"
weight = 2
