import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LanguageSwitcher from "@/components/layout/LanguageSwitcher";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-black`}
    >
      <body className="min-h-full flex flex-col">
        <header className="w-full bg-black border-b border-gray-800 text-white">
          <div className="container mx-auto px-4 h-16 flex items-center justify-between">
            <Link href={`/${lang}`} className="font-bold text-xl tracking-tight">AquaFit</Link>
            <div className="flex items-center gap-4">
              <LanguageSwitcher currentLang={lang} />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
