import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UnitProvider } from "@/contexts/UnitContext";
import UnitSwitcher from "@/components/layout/UnitSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-black`}
    >
      <body className="min-h-full flex flex-col">
        <UnitProvider>
          <header className="w-full bg-black border-b border-gray-800 text-white">
            <div className="container mx-auto px-4 h-16 flex items-center justify-between">
              <Link href="/" className="font-bold text-xl tracking-tight">AquaFit</Link>
              <div className="flex items-center gap-4">
                <UnitSwitcher />
              </div>
            </div>
          </header>
          {children}
        </UnitProvider>
      </body>
    </html>
  );
}
