name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Simple content generation
        run: |
          echo "=== ПРОСТАЯ ГЕНЕРАЦИЯ ==="
          DATE=$(date +%Y-%m-%d)
          FILE="content/posts/${DATE}-simple-article.md"
          
          cat > "$FILE" << 'EOL'
---
title: "Тестовая статья"
date: 2024-01-15T12:00:00Z
draft: false
tags: ["тест"]
---

# Тестовая статья

Это простая тестовая статья для проверки работы workflow.

## Сгенерировано автоматически
EOL
          
          echo "✅ Файл создан: $FILE"

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add content/posts/
          git commit -m "🤖 Тестовая статья" || echo "Нет изменений"
          git push
