name: AI Content Generator

on:
  schedule:
    - cron: '0 11 * * *'  # Ежедневно в 11:00 UTC
  workflow_dispatch:       # Ручной запуск

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create directory structure
      run: |
        echo "📁 Creating directory structure..."
        mkdir -p content/posts
        mkdir -p assets/images/posts
        mkdir -p static/css
        mkdir -p layouts/_default
        mkdir -p layouts/partials
        echo "✅ Directories created"

    - name: Generate sample content
      run: |
        echo "📝 Generating sample content..."
        
        # Create simple Python script to generate content
        cat > generate_sample.py << 'EOF'
import os
import random
from datetime import datetime, timedelta

def generate_sample_content():
    print("🔄 Generating sample AI content...")
    
    topics = [
        "Искусственный интеллект в 2025 году: основные тренды и перспективы",
        "Нейросети и глубокое обучение: современные достижения",
        "Генеративные AI модели: от GPT до Stable Diffusion",
        "Этика искусственного интеллекта: проблемы и решения",
        "Машинное обучение в медицине: диагностика и лечение",
        "Компьютерное зрение: новые возможности и применения",
        "Natural Language Processing: понимание и генерация текста",
        "Автономные системы и робототехника с использованием AI"
    ]
    
    os.makedirs("content/posts", exist_ok=True)
    os.makedirs("assets/images/posts", exist_ok=True)
    
    # Generate 3-5 articles
    num_articles = random.randint(3, 5)
    
    for i in range(num_articles):
        topic = random.choice(topics)
        # Use different dates for variety
        date = (datetime.now() - timedelta(days=random.randint(0, 7))).strftime("%Y-%m-%d")
        slug = f"ai-article-{i+1}-{datetime.now().strftime('%H%M')}"
        filename = f"content/posts/{date}-{slug}.md"
        
        content = f"""---
title: "{topic}"
date: {date}
tags: ["AI", "технологии", "2025", "нейросети"]
draft: false
image: "/images/posts/ai-banner.jpg"
---

## Введение
{topic} представляет собой одно из наиболее exciting направлений в современной компьютерной науке. 

## Основные аспекты
- **Технологические инновации**: Новые алгоритмы и архитектуры нейросетей
- **Практическое применение**: Реальные кейсы использования в различных отраслях
- **Будущее развитие**: Перспективы и потенциальные прорывы

## Технические детали
Современные системы искусственного интеллекта основаны на передовых технологиях машинного обучения, включая глубокие нейронные сети, трансформеры и генеративные модели.

## Примеры использования
- Автоматическая обработка и анализ данных
- Генерация контента и творческие задачи
- Прогностическая аналитика и принятие решений

## Заключение
{topic} продолжает rapidly развиваться, предлагая новые возможности для исследователей, разработчиков и бизнеса. Будущее искусственного интеллекта выглядит extremely promising.
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Created: {filename}")
    
    print(f"📊 Generated {num_articles} articles")

if __name__ == "__main__":
    generate_sample_content()
EOF
        
        # Run the generator
        python generate_sample.py

    - name: List generated files
      run: |
        echo "📁 Generated content:"
        find content/ -name "*.md" -exec echo "   📄 {}" \;
        echo "Total articles: $(find content/ -name "*.md" | wc -l)"

    - name: Commit and push generated content
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        
        # Add only content and assets
        git add content/ assets/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "ℹ️ No changes to commit"
        else
          git commit -m "🤖 Auto-generated AI content: $(date +'%Y-%m-%d %H:%M')"
          git push origin main
          echo "✅ Changes pushed to repository"
        fi

    - name: Show workflow status
      run: |
        echo "🎉 AI Content Generator completed successfully!"
        echo "🌐 Website will update on next deployment"
        echo "🕒 Next scheduled run: daily at 11:00 UTC"
