name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate content
        run: |
          echo "=== ГЕНЕРАЦИЯ КОНТЕНТА ==="
          
          # Локальная генерация контента
          TOPICS=(
            "Современные фреймворки веб-разработки в 2024 году"
            "Искусственный интеллект в веб-приложениях"
            "Прогрессивные веб-приложения (PWA) против нативных"
            "Серверless архитектура: преимущества и вызовы"
            "Кибербезопасность в современном вебе"
          )
          
          # Выбираем случайную тему
          SELECTED_TOPIC="${TOPICS[$((RANDOM % ${#TOPICS[@]}))]}"
          
          # Генерируем контент на основе темы
          case $SELECTED_TOPIC in
            *фреймворки*)
              CONTENT="В 2024 году популярность набирают фреймворки like React, Vue 3, и Svelte. Next.js и Nuxt.js доминируют в full-stack разработке. Важным трендом стало использование TypeScript для улучшения качества кода."
              ;;
            *интеллект*)
              CONTENT="AI революционизирует веб-разработку: чат-боты на базе GPT, генерация контента, персонализация пользовательского опыта. Интеграция ML-моделей прямо в браузер через WebAssembly."
              ;;
            *PWA*)
              CONTENT="PWA продолжают развиваться, предлагая нативный опыт без установки. Новые Web API позволяют доступ к hardware функциям. Offline-работа и push-уведомления становятся стандартом."
              ;;
            *серверless*)
              CONTENT="Serverless архитектура снижает затраты на инфраструктуру. Cloud Functions, Edge Computing и микросервисы позволяют масштабироваться автоматически. Важен правильный выбор провайдера: AWS Lambda, Cloud Functions, Vercel."
              ;;
            *безопасность*)
              CONTENT="Кибербезопасность критически важна: OWASP Top 10, HTTPS обязателен, защита от XSS и CSRF атак. Биометрическая аутентификация и 2FA становятся стандартом для веб-приложений."
              ;;
            *)
              CONTENT="Веб-разработка в 2024 характеризуется rapid evolution технологий. Акцент на производительность, доступность и пользовательский опыт. JAMstack, AI интеграция и serverless доминируют в индустрии."
              ;;
          esac
          
          echo "📝 Тема: $SELECTED_TOPIC"
          echo "📄 Контент: $CONTENT"
          
          # Создаем статью
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          echo "---" > "$FILE"
          echo "title: \"$SELECTED_TOPIC\"" >> "$FILE"
          echo "date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
          echo "draft: false" >> "$FILE"
          echo "description: \"Автоматически сгенерированная статья\"" >> "$FILE"
          echo "tags: [\"веб-разработка\", \"технологии\", \"2024\"]" >> "$FILE"
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "# $SELECTED_TOPIC" >> "$FILE"
          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"
          echo "" >> "$FILE"
          echo "## 🔧 Технологический стек" >> "$FILE"
          echo "" >> "$FILE"
          echo "- **Фронтенд:** React, Vue, Svelte" >> "$FILE"
          echo "- **Бэкенд:** Node.js, Python, Go" >> "$FILE"
          echo "- **Базы данных:** PostgreSQL, MongoDB, Redis" >> "$FILE"
          echo "- **Инфраструктура:** Docker, Kubernetes, AWS" >> "$FILE"
          echo "" >> "$FILE"
          echo "> *Статья сгенерирована автоматически $(date +"%d.%m.%Y")*" >> "$FILE"
          
          echo "✅ Файл создан: $FILE"

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Автоматическая статья: $(date +"%d.%m.%Y")"
            git pull origin main --rebase
            git push origin main
            echo "✅ Статья добавлена!"
          else
            echo "❌ Нет изменений для коммита"
          fi

      - name: Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Последние файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; | tail -3
