name: AI Content Generator

on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC (15:00 МСК)
  workflow_dispatch:  # Ручной запуск

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-content:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Europe/Moscow
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Убираем автоматическое определение зависимостей

    - name: Install Python dependencies
      run: |
        echo "📦 Установка Python зависимостей..."
        python -m pip install --upgrade pip
        pip install requests

    - name: Check repository structure
      run: |
        echo "🔍 Проверка структуры репозитория..."
        echo "📁 Содержимое корневой папки:"
        ls -la
        
        echo "📁 Содержимое .github:"
        ls -la .github/ || echo "Папка .github не найдена"
        
        echo "📁 Содержимое .github/scripts:"
        ls -la .github/scripts/ || echo "Папка .github/scripts не найдена"
        
        echo "🔎 Поиск generate_content.py:"
        find . -name "generate_content.py" -type f 2>/dev/null || echo "Файл не найден"

    - name: Create necessary directories
      run: |
        echo "📁 Создание структуры папок..."
        mkdir -p content/posts
        mkdir -p assets/images/posts
        mkdir -p static/css
        mkdir -p layouts/_default
        mkdir -p layouts/partials
        echo "✅ Папки созданы"

    - name: Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        STABILITYAI_KEY: ${{ secrets.STABILITYAI_KEY }}
      run: |
        echo "🚀 Запуск генерации контента..."
        
        # Создаем простой скрипт если основной не найден
        if [ ! -f ".github/scripts/generate_content.py" ]; then
            echo "⚠️ Основной скрипт не найден, создаем простую версию..."
            cat > simple_generate.py << 'EOF'
#!/usr/bin/env python3
import os
import random
from datetime import datetime

def generate_simple_content():
    print("🔄 Используем простой генератор контента")
    
    topics = [
        "Искусственный интеллект в 2025 году: основные тренды",
        "Нейросети и машинное обучение: будущее технологий",
        "Генеративные AI модели: новые возможности",
        "Этика искусственного интеллекта: вызовы и решения",
        "AI в медицине: революция в диагностике"
    ]
    
    os.makedirs("content/posts", exist_ok=True)
    
    for i in range(2):
        topic = random.choice(topics)
        date = datetime.now().strftime("%Y-%m-%d")
        slug = f"ai-article-{i+1}"
        filename = f"content/posts/{date}-{slug}.md"
        
        content = f"""---
title: "{topic}"
date: {date}
tags: ["AI", "технологии", "2025"]
draft: false
---

## Введение
{topic} - это важное направление в современном мире технологий.

## Основные аспекты
- **Инновации**: Новые технологии меняют наш подход к решению задач
- **Применение**: Широкие возможности использования в различных отраслях
- **Перспективы**: Большой потенциал для будущего развития

## Технические детали
Современные системы искусственного интеллекта используют передовые алгоритмы машинного обучения.

## Заключение
{topic} представляет собой перспективное направление с огромными возможностями для инноваций.
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Создана статья: {filename}")
    
    print("📝 Контент создан успешно")

if __name__ == "__main__":
    generate_simple_content()
EOF
            
            python simple_generate.py
        else
            echo "📝 Найден скрипт в .github/scripts/generate_content.py"
            cd .github/scripts/
            python generate_content.py
            cd ../../
        fi
        
        echo "✅ Генерация завершена"
        echo "📁 Проверка созданных файлов:"
        
        find content/ -name "*.md" -exec echo "📄 {}" \; 2>/dev/null || echo "⚠️ Статьи не найдены"
        find assets/ -name "*.jpg" -o -name "*.png" -exec echo "🖼️ {}" \; 2>/dev/null || echo "⚠️ Изображения не найдены"

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.125.7'
        extended: true

    - name: Build Hugo site
      run: |
        echo "🏗️ Сборка сайта Hugo..."
        echo "📊 Версия Hugo:"
        hugo version
        
        echo "📁 Структура перед сборкой:"
        echo "content/: $(ls -la content/ 2>/dev/null | wc -l) файлов"
        echo "layouts/: $(ls -la layouts/ 2>/dev/null | wc -l) файлов"
        echo "static/: $(ls -la static/ 2>/dev/null | wc -l) файлов"
        
        # Сборка
        hugo --minify --logLevel info
        
        echo "📁 Результат сборки:"
        if [ -d "public" ]; then
            echo "✅ Папка public создана"
            echo "HTML файлов: $(find public/ -name "*.html" | wc -l)"
            echo "Размер: $(du -sh public/ | cut -f1)"
        else
            echo "❌ Папка public не создана"
            exit 1
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        keep_files: false

    - name: Verify deployment
      run: |
        echo "✅ Workflow успешно завершен!"
        echo "🌐 Сайт будет доступен по адресу: https://lybra-bee.github.io"
        echo "🕒 Время завершения: $(date '+%Y-%m-%d %H:%M:%S %Z')"
