name: AI Content Generator

on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC (15:00 МСК)
  workflow_dispatch:  # Ручной запуск

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create generate_content.py script
      run: |
        echo "📝 Создание generate_content.py..."
        cat > generate_content.py << 'EOF'
import os
import random
from datetime import datetime, timedelta

def main():
    print("🔄 Запуск генерации контента...")
    
    topics = [
        "Искусственный интеллект в 2025 году: основные тренды",
        "Нейросети и машинное обучение: современные достижения",
        "Генеративные AI модели: создание контента и кода",
        "AI в медицине: диагностика и разработка лекарств",
        "Компьютерное зрение: новые возможности распознавания",
        "Обработка естественного языка: понимание контекста",
        "Автономные системы и робототехника",
        "Этика искусственного интеллекта: ответственное развитие"
    ]
    
    os.makedirs("content/posts", exist_ok=True)
    os.makedirs("assets/images/posts", exist_ok=True)
    
    # Создаем 3-4 статьи
    for i in range(random.randint(3, 4)):
        topic = random.choice(topics)
        date = (datetime.now() - timedelta(days=i)).strftime("%Y-%m-%d")
        filename = f"content/posts/{date}-ai-article-{i+1}.md"
        
        content = f"""---
title: "{topic}"
date: {date}
tags: ["AI", "машинное обучение", "технологии", "2025"]
draft: false
---

## Введение
{topic} представляет собой rapidly развивающуюся область с огромным потенциалом.

## Основные направления
- **Технологические инновации**: Новые алгоритмы и архитектуры нейросетей
- **Практическое применение**: Реальные кейсы использования в различных отраслях
- **Будущее развитие**: Перспективы и потенциальные прорывы

## Технические детали
Современные системы искусственного интеллекта используют передовые технологии машинного обучения, включая глубокие нейронные сети, трансформеры и генеративные модели.

## Заключение
{topic} продолжает revolutionизировать различные отрасли и открывать новые возможности для инноваций.
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Создана статья: {filename}")
    
    print("🎉 Генерация контента завершена!")

if __name__ == "__main__":
    main()
EOF

    - name: Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "🔍 Проверка структуры папок..."
        ls -la
        
        echo "🚀 Запуск генерации контента..."
        python generate_content.py
        
        echo "📁 Проверка созданных файлов:"
        find content/ -name "*.md" -exec ls -la {} \; || echo "Нет Markdown файлов"
        find assets/ -name "*.jpg" -exec ls -la {} \; || echo "Нет изображений"

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.125.7'
        extended: true

    - name: Build site
      run: |
        echo "🏗️ Сборка сайта Hugo..."
        hugo --minify --logLevel info
        
        echo "📁 Содержимое public/:"
        ls -la public/ || echo "Папка public/ не создана"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        keep_files: false

    - name: Verify deployment
      run: |
        echo "✅ Workflow завершен"
        echo "🌐 Сайт должен быть доступен по адресу: https://lybra-bee.github.io"
        echo "🕒 Обновление может занять 1-2 минуты"
