name: AI Content Generator

on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC (15:00 МСК)
  workflow_dispatch:  # Ручной запуск

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "🔑 Проверка переменных окружения..."
        echo "OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:0:5}..." 
        echo "GROQ_API_KEY: ${GROQ_API_KEY:0:5}..."
        echo "🚀 Запуск генерации контента..."
        python .github/scripts/generate_content.py

    - name: Commit generated content
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add content/posts/ assets/images/
        git diff --cached --quiet || git commit -m "Auto-generated content [skip ci]"
        git push

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.125.7'
        extended: true

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
