name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Cleanup old structure
        run: |
          echo "🧹 Очищаем старую структуру..."
          rm -rf content/posts/posts/ 2>/dev/null || true
          rm -rf content/posts/projects/ 2>/dev/null || true

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate article with AI test
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "=== ТЕСТИРУЕМ API HUGGING FACE ==="
          echo "Длина HF_API_KEY: ${#HF_API_KEY} символов"
          
          if [ -z "$HF_API_KEY" ] || [ "$HF_API_KEY" == "" ]; then
            echo "❌ HF_API_KEY не настроен или пустой!"
            CONTENT="Ошибка: API ключ не настроен. Добавьте HF_API_KEY в Settings → Secrets → Actions"
          else
            echo "🔌 Проверяем подключение к API..."
            echo "Используем модель: microsoft/DialoGPT-large"
            
            # Тестовый запрос к работающей модели
            response=$(curl -s -X POST \
              -H "Authorization: Bearer $HF_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{
                "inputs": "Напиши один абзац о современных веб-технологиях:",
                "parameters": {
                  "max_new_tokens": 150,
                  "temperature": 0.8,
                  "do_sample": true
                }
              }' \
              "https://api-inference.huggingface.co/models/microsoft/DialoGPT-large" 2>&1)
            
            echo "=== ОТВЕТ API ==="
            echo "$response"
            echo "=== КОНЕЦ ОТВЕТА ==="
            
            if [[ "$response" == *"generated_text"* ]]; then
              echo "✅ API подключено успешно!"
              CONTENT=$(echo "$response" | python3 -c "import json, sys; data=json.load(sys.stdin); print(data[0]['generated_text'])" | head -5)
            elif [[ "$response" == *"error"* ]]; then
              echo "⚠️ Ошибка API, но ключ работает"
              CONTENT="API временно недоступно. Ключ настроен правильно, но модель не отвечает."
            else
              echo "❌ Неизвестная ошибка API"
              CONTENT="Ошибка подключения к AI API. Проверьте логи для деталей."
            fi
          fi
          
          echo "📝 Создаем статью..."
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          # Создаем статью
          echo "---" > "$FILE"
          echo "title: \"AI Статья от ${TIMESTAMP}\"" >> "$FILE"
          echo "date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
          echo "draft: false" >> "$FILE"
          echo "description: \"Статья создана автоматически с AI\"" >> "$FILE"
          echo "tags: [\"ai\", \"автоматизация\", \"тест\"]" >> "$FILE"
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "# 🚀 AI Генерация контента" >> "$FILE"
          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"
          echo "" >> "$FILE"
          echo "## 📊 Технические детали" >> "$FILE"
          echo "" >> "$FILE"
          echo "- **Дата генерации:** $(date +"%Y-%m-%d %H:%M:%S")" >> "$FILE"
          echo "- **Модель:** Microsoft DialoGPT-large" >> "$FILE"
          echo "- **Статус API:** $(if [[ "$response" == *"generated_text"* ]]; then echo '✅ Успешно'; else echo '⚠️ Ошибка'; fi)" >> "$FILE"
          echo "- **Длина ключа:** ${#HF_API_KEY} символов" >> "$FILE"
          echo "" >> "$FILE"
          echo "> *Сгенерировано автоматически через GitHub Actions + Hugging Face API*" >> "$FILE"
          
          echo "✅ Файл создан: $FILE"
          echo "📄 Предпросмотр:"
          head -20 "$FILE"

      - name: Commit changes
        run: |
          echo "=== КОММИТ ИЗМЕНЕНИЙ ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          git status
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Тест AI-генерации от $(date +%Y-%m-%d_%H-%M-%S)"
            git pull origin main --rebase
            git push origin main
            echo "✅ Статья добавлена!"
          else
            echo "❌ Нет изменений для коммита"
            echo "Содержимое папки posts:"
            ls -la content/posts/
          fi

      - name: Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Последние файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; | tail -5
          echo "Всего статей:"
          find content/posts/ -name "*.md" -type f | wc -l
