name: AI Content Generator

on:
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles to generate'
        required: true
        default: '1'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
  schedule:
    - cron: '0 8 * * *'  # Каждый день в 8:00 UTC

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        pip install requests pillow python-dotenv feedparser

    - name: 📁 Create content directories
      run: |
        mkdir -p content/posts
        mkdir -p static/images/posts

    - name: 🤖 Generate AI content
      run: |
        python .github/scripts/generate_content.py --count ${{ github.event.inputs.article_count }} --debug

    - name: 💾 Commit and push generated content
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Обновляем локальную копию
        git fetch origin
        git reset --hard origin/main
        
        # Добавляем только новые файлы
        git add content/posts/
        git add static/images/posts/
        
        # Коммит если есть изменения
        if ! git diff --cached --quiet; then
            git commit -m "Auto-generated AI content $(date +'%Y-%m-%d %H:%M')"
            git push origin main
            echo "✅ Изменения отправлены успешно"
        else
            echo "✅ Нет новых изменений для коммита"
        fi

  notify:
    runs-on: ubuntu-latest
    needs: generate-content
    if: always()
    steps:
    - name: 📨 Send notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          MESSAGE="✅ Генерация контента завершена успешно! $(date +'%Y-%m-%d %H:%M')"
        else
          MESSAGE="❌ Ошибка генерации контента. Статус: ${{ job.status }}"
        fi
        
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MESSAGE\"}"
