name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Cleanup old structure
        run: |
          echo "🧹 Очищаем старую структуру..."
          rm -rf content/posts/posts/ 2>/dev/null || true
          rm -rf content/posts/projects/ 2>/dev/null || true

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Test API connection
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "=== ТЕСТ ПОДКЛЮЧЕНИЯ API ==="
          echo "Проверяем валидность API ключа..."
          
          # Простой запрос к API для проверки ключа
          response=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Bearer $HF_API_KEY" \
            "https://huggingface.co/api/whoami")
          
          status_code=$(echo "$response" | tail -1)
          body=$(echo "$response" | head -n -1)
          
          echo "Status Code: $status_code"
          echo "Response: $body"
          
          if [ "$status_code" -eq 200 ]; then
            echo "✅ API ключ валиден!"
          else
            echo "❌ API ключ невалиден или ошибка доступа"
            echo "Проверьте HF_API_KEY в настройках репозитория"
          fi

      - name: Generate article with AI test
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "=== ТЕСТИРУЕМ РАБОЧИЕ МОДЕЛИ ==="
          
          if [ -z "$HF_API_KEY" ] || [ "$HF_API_KEY" == "" ]; then
            echo "❌ HF_API_KEY не настроен!"
            CONTENT="Ошибка: API ключ не настроен."
          else
            echo "🔌 Опрашиваем гарантированно рабочие модели..."
            
            # Гарантированно рабочие модели для текстовой генерации
            MODELS=(
              "google/flan-t5-small"
              "facebook/bart-large-cnn"
              "microsoft/DialoGPT-small"
              "valhalla/t5-small-qa"
            )
            
            CONTENT=""
            SUCCESS_MODEL=""
            
            for model in "${MODELS[@]}"; do
              echo "---"
              echo "🔄 Пробуем модель: $model"
              
              response=$(curl -s -X POST \
                -H "Authorization: Bearer $HF_API_KEY" \
                -H "Content-Type: application/json" \
                -d '{
                  "inputs": "Объясни что такое веб-разработка:",
                  "parameters": {
                    "max_new_tokens": 100,
                    "temperature": 0.7
                  }
                }' \
                "https://api-inference.huggingface.co/models/$model" 2>&1)
              
              echo "Ответ: ${response:0:200}..."
              
              if [[ "$response" == *"generated_text"* ]]; then
                echo "✅ Успех! Модель $model работает!"
                CONTENT=$(echo "$response" | python3 -c "import json, sys; data=json.load(sys.stdin); print(data[0]['generated_text'])" | head -8)
                SUCCESS_MODEL="$model"
                break
              elif [[ "$response" == *"error"* ]]; then
                echo "⚠️ Ошибка модели: $response"
              else
                echo "❌ Неизвестный ответ от модели"
              fi
              
              sleep 1
            done
            
            if [ -z "$CONTENT" ]; then
              echo "❌ Ни одна модель не сработала"
              CONTENT="Проверка API: все модели возвращают ошибки. Возможно, проблема с форматом запроса или API endpoint."
              SUCCESS_MODEL="error"
            fi
          fi
          
          echo "📝 Создаем статью..."
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          # Создаем статью
          echo "---" > "$FILE"
          echo "title: \"AI Статья от ${TIMESTAMP}\"" >> "$FILE"
          echo "date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
          echo "draft: false" >> "$FILE"
          echo "description: \"Тестирование Hugging Face API\"" >> "$FILE"
          echo "tags: [\"ai\", \"тест\", \"api\"]" >> "$FILE"
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "# 🚀 Тестирование AI Генерации" >> "$FILE"
          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"
          echo "" >> "$FILE"
          echo "## 📊 Детали теста" >> "$FILE"
          echo "" >> "$FILE"
          echo "- **Дата:** $(date +"%Y-%m-%d %H:%M:%S")" >> "$FILE"
          echo "- **Модель:** ${SUCCESS_MODEL:-none}" >> "$FILE"
          echo "- **Статус:** $(if [ "$SUCCESS_MODEL" != "error" ]; then echo '✅ Успешно'; else echo '❌ Ошибка'; fi)" >> "$FILE"
          echo "- **Длина ключа:** ${#HF_API_KEY} символов" >> "$FILE"
          echo "" >> "$FILE"
          echo "> *Тестовый запуск для отладки API*" >> "$FILE"
          
          echo "✅ Файл создан: $FILE"

      - name: Commit changes
        run: |
          echo "=== КОММИТ ИЗМЕНЕНИЙ ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          git status
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Тест API от $(date +%Y-%m-%d_%H-%M-%S)"
            git pull origin main --rebase
            git push origin main
            echo "✅ Статья добавлена!"
          else
            echo "❌ Нет изменений для коммита"
            ls -la content/posts/
          fi

      - name: Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Последние файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; | tail -3
