name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate with OpenRouter AI
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          echo "=== РЕАЛЬНАЯ ГЕНЕРАЦИЯ ЧЕРЕЗ OPENROUTER ==="
          
          # Бесплатные модели на OpenRouter
          FREE_MODELS=(
            "google/palm-2-chat-bison-32k:free"
            "mistralai/mistral-7b-instruct:free" 
            "huggingfaceh4/zephyr-7b-beta:free"
            "anthropic/claude-3-haiku:free"
          )
          
          # Случайные темы для статей
          TOPICS=(
            "Веб-фреймворки 2024: React, Vue, Svelte сравнение"
            "Serverless архитектура для веб-приложений"
            "Искусственный интеллект в веб-разработке"
            "Прогрессивные веб-приложения (PWA) новые возможности"
            "Кибербезопасность современных веб-приложений"
            "WebAssembly и высокопроизводительные веб-приложения"
            "JAMstack архитектура и статические генераторы"
            "Микросервисы vs монолиты в веб-разработке"
            "TypeScript vs JavaScript в современной разработке"
            "GraphQL vs REST API: что выбрать в 2024"
          )
          
          SELECTED_MODEL=${FREE_MODELS[$RANDOM % ${#FREE_MODELS[@]}]}
          SELECTED_TOPIC=${TOPICS[$RANDOM % ${#TOPICS[@]}]}
          
          echo "🎯 Модель: $SELECTED_MODEL"
          echo "📝 Тема: $SELECTED_TOPIC"
          
          # Генерация контента через OpenRouter
          response=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENROUTER_API_KEY" \
            -H "HTTP-Referer: https://lybra-bee.github.io" \
            -H "X-Title: AI Blog Generator" \
            -d '{
              "model": "'"$SELECTED_MODEL"'",
              "messages": [
                {
                  "role": "user", 
                  "content": "Напиши развернутую техническую статью на тему: '"$SELECTED_TOPIC"'. Используй Markdown для форматирования, подзаголовки ##, **жирный шрифт** для ключевых терминов. Ответ должен быть на русском языке, объемом 300-500 слов. Сделай статью информативной и полезной для разработчиков."
                }
              ],
              "max_tokens": 800,
              "temperature": 0.7,
              "top_p": 0.9
            }' \
            "https://openrouter.ai/api/v1/chat/completions" 2>/dev/null || echo "API_ERROR")
          
          if [[ "$response" == *"choices"* ]] && [[ "$response" != *"error"* ]]; then
            echo "✅ Генерация успешна!"
            CONTENT=$(echo "$response" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    content = data['choices'][0]['message']['content']
    # Очищаем от возможных лишних кавычек
    content = content.replace('\"\"\"', '').replace('\'\'\'', '')
    print(content)
except Exception as e:
    print('Ошибка парсинга ответа API:', str(e))
    exit(1)
")
          else
            echo "❌ Ошибка API: $response"
            echo "🔄 Используем локальную генерацию..."
            # Локальный fallback контент
            case $SELECTED_TOPIC in
              *фреймворки*)
                CONTENT="## Современные веб-фреймворки 2024\n\nВ 2024 году **React** продолжает доминировать с новыми функциями Concurrent Rendering и Server Components. **Vue 3** с Composition API набирает популярность для сложных приложений благодаря лучшей TypeScript поддержке. **Svelte** предлагает innovative компиляторный подход с минимальным runtime overhead.\n\n**Next.js** и **Nuxt.js** остаются лидерами для full-stack разработки, предлагая SSR, SSG и API routes из коробки. Новые метафреймворки like **Astro** и **Qwik** focus на производительности и частичной гидратации.\n\n### Критерии выбора\n\n- **Производительность**: Svelte > Vue > React\n- **Экосистема**: React > Vue > Svelte  \n- **Кривая обучения**: Vue < React < Svelte\n- **TypeScript поддержка**: Vue 3 > React > Svelte"
                ;;
              *Serverless*)
                CONTENT="## Serverless архитектура\n\nServerless революционизирует веб-разработку, позволяя разработчикам focus на бизнес-логике вместо инфраструктуры. **AWS Lambda**, **Cloud Functions** и **Vercel Edge Functions** обеспечивают автоматическое масштабирование и pay-per-use модель.\n\n### Преимущества\n\n- **Reduced operational overhead**: Нет необходимости управлять серверами\n- **Cost efficiency**: Платите только за реальное использование\n- **Автоматическое масштабирование**: Обрабатывайте тысячи запросов без дополнительной настройки\n- **Глобальная доступность**: Развертывание в нескольких регионах\n\n### Вызовы\n\n- **Cold starts**: Задержка при первом запуске функции\n- **Debugging**: Сложнее отлаживать распределенные системы\n- **Vendor lock-in**: Привязка к конкретному cloud провайдеру\n- **Ограничения**: Лимиты времени выполнения и памяти"
                ;;
              *интеллект*)
                CONTENT="## AI в веб-разработке\n\nИскусственный интеллект трансформирует веб-разработку: **GPT-4** для генерации контента, **Copilot** для assistance в coding, **AI-powered chatbots** для customer service.\n\n### Практические применения\n\n- **Генерация кода**: Автоматическое создание компонентов и функций\n- **Тестирование**: AI-generated test cases и bug detection\n- **Оптимизация**: Автоматическое улучшение производительности\n- **Доступность**: AI-powered accessibility checking\n\n### Технологии\n\nНовые API like **WebGPU** позволяют запускать ML модели прямо в браузере. **AutoML** platforms упрощают интеграцию AI без deep learning экспертизы. **TensorFlow.js** и **ONNX Runtime** обеспечивают inference в браузере.\n\n### Будущее\n\nК 2025 году ожидается интеграция AI в большинство инструментов разработки. Low-code платформы с AI станут стандартом для бизнес-приложений."
                ;;
              *)
                CONTENT="## $SELECTED_TOPIC\n\nСовременная веб-разработка в 2024 характеризуется rapid innovation и convergence технологий. **React 18** и **Vue 3** задают стандарты frontend развития с улучшенной производительностью и developer experience.\n\n**Serverless архитектура** reduces operational complexity и позволяет teams focus на product development. **WebAssembly** enables near-native performance в браузере, открывая новые возможности для сложных приложений.\n\n**AI интеграция** становится must-have для персонализации и automation. **Кибербезопасность** критически важна в era увеличивающихся атак и regulations like GDPR и CCPA.\n\n### Тренды 2024\n\n- **Edge computing**: Выполнение кода ближе к пользователю\n- **Zero trust security**: Постоянная верификация и минимальные привилегии  \n- **Web3 интеграция**: Децентрализованные приложения и цифровые активы\n- **Sustainable web**: Энергоэффективная разработка и green hosting"
                ;;
            esac
          fi
          
          echo "📄 Сгенерированный контент:"
          echo "---"
          echo "$CONTENT" | head -10
          echo "..."
          echo "---"
          
          # Создаем статью
          DATE=$(date +%Y-%m-%d)
          SLUG=$(echo "$SELECTED_TOPIC" | tr ' ' '-' | tr 'А-Яа-я' 'A-Za-z' | tr -cd '[:alnum:]-' | head -c 40 | tr 'A-Z' 'a-z')
          FILE="content/posts/${DATE}-${SLUG}.md"
          
          cat > "$FILE" << EOF
---
title: "$SELECTED_TOPIC"
date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
draft: false
description: "Автоматически сгенерированная статья о $SELECTED_TOPIC"
tags: ["веб-разработка", "технологии", "2024"]
categories: ["Разработка"]
---

# $SELECTED_TOPIC

$CONTENT

---

### 🔧 Технические детали

- **Модель AI:** ${SELECTED_MODEL:-"Локальная генерация"}
- **Дата генерации:** $(date +"%d.%m.%Y %H:%M UTC")
- **Тема:** $SELECTED_TOPIC
- **Статус:** ✅ Автоматически сгенерировано

> *Сгенерировано через OpenRouter API + GitHub Actions*
EOF
          
          echo "✅ Файл создан: $FILE"
          echo "📝 Предпросмотр:"
          head -15 "$FILE"

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          git status
          
          if git diff --staged --quiet; then
            echo "❌ Нет изменений для коммита"
            echo "Содержимое папки content/posts/:"
            ls -la content/posts/
            exit 0
          fi
          
          git commit -m "🤖 AI Статья: $SELECTED_TOPIC [$(date +"%d.%m.%Y %H:%M")]"
          git pull --rebase
          git push
          echo "✅ Статья успешно добавлена и запущена!"

      - name: Verify results
        run: |
          echo "=== РЕЗУЛЬТАТЫ ГЕНЕРАЦИИ ==="
          echo "Последние созданные файлы:"
          find content/posts/ -name "*.md" -exec ls -la {} \; | tail -3
          echo "Всего статей в папке:"
          find content/posts/ -name "*.md" | wc -l
