name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate with DeepSeek API
        run: |
          echo "=== ИСПОЛЬЗУЕМ DEEPSEEK API ==="
          
          # DeepSeek API (бесплатный аналог)
          response=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "model": "deepseek-chat",
              "messages": [
                {"role": "user", "content": "Напиши короткий абзац о современных веб-технологиях 2024 года"}
              ],
              "temperature": 0.7,
              "max_tokens": 300
            }' \
            "https://api.deepseek.com/v1/chat/completions" 2>&1 || echo "API_ERROR")
          
          echo "Ответ DeepSeek: $response"
          
          if [[ "$response" == *"choices"* ]]; then
            echo "✅ DeepSeek API сработал!"
            CONTENT=$(echo "$response" | python3 -c "import json, sys; data=json.load(sys.stdin); print(data['choices'][0]['message']['content'])" | head -10)
          else
            echo "❌ DeepSeek не сработал, используем локальную генерацию"
            CONTENT="Современная веб-разработка в 2024 году характеризуется использованием продвинутых фреймворков like React и Vue, серверless-архитектур, и AI-интеграций. DevOps и автоматизация стали неотъемлемой частью процесса."
          fi
          
          echo "📝 Создаем статью..."
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          echo "---" > "$FILE"
          echo "title: \"Современные веб-технологии 
