name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Cleanup old structure
        run: |
          echo "🧹 Очищаем старую структуру..."
          rm -rf content/posts/posts/ 2>/dev/null || true
          rm -rf content/posts/projects/ 2>/dev/null || true

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate article with AI test
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "=== ТЕСТИРУЕМ РАЗЛИЧНЫЕ МОДЕЛИ ==="
          echo "Длина HF_API_KEY: ${#HF_API_KEY} символов"
          
          if [ -z "$HF_API_KEY" ] || [ "$HF_API_KEY" == "" ]; then
            echo "❌ HF_API_KEY не настроен или пустой!"
            CONTENT="Ошибка: API ключ не настроен. Добавьте HF_API_KEY в Settings → Secrets → Actions"
          else
            echo "🔌 Опрашиваем модели по очереди..."
            
            # Список моделей для опроса (в порядке приоритета)
            MODELS=(
              "deepseek-ai/DeepSeek-V3"
              "deepseek-ai/deepseek-llm-7b"
              "microsoft/DialoGPT-medium"
              "gpt2"
              "distilgpt2"
              "facebook/blenderbot-400M-distill"
            )
            
            CONTENT=""
            SUCCESS_MODEL=""
            
            for model in "${MODELS[@]}"; do
              echo "---"
              echo "🔄 Пробуем модель: $model"
              
              response=$(curl -s -X POST \
                -H "Authorization: Bearer $HF_API_KEY" \
                -H "Content-Type: application/json" \
                -d '{
                  "inputs": "Напиши короткий абзац о современных веб-технологиях и трендах разработки:",
                  "parameters": {
                    "max_new_tokens": 150,
                    "temperature": 0.8,
                    "do_sample": true
                  }
                }' \
                "https://api-inference.huggingface.co/models/$model" 2>&1)
              
              if [[ "$response" == *"generated_text"* ]]; then
                echo "✅ Успех! Модель $model работает!"
                CONTENT=$(echo "$response" | python3 -c "import json, sys; data=json.load(sys.stdin); print(data[0]['generated_text'])" | head -10)
                SUCCESS_MODEL="$model"
                break
              elif [[ "$response" == *"404"* ]] || [[ "$response" == *"Not Found"* ]]; then
                echo "❌ Модель $model не найдена"
              elif [[ "$response" == *"503"* ]] || [[ "$response" == *"loading"* ]]; then
                echo "⏳ Модель $model загружается, пробуем следующую"
              elif [[ "$response" == *"401"* ]] || [[ "$response" == *"Authorization"* ]]; then
                echo "🔐 Ошибка авторизации, прерываем"
                CONTENT="Ошибка авторизации API. Проверьте API ключ."
                break
              else
                echo "❌ Ошибка с моделью $model: $response"
              fi
              
              # Небольшая пауза между запросами
              sleep 2
            done
            
            if [ -z "$CONTENT" ]; then
              echo "❌ Ни одна модель не сработала"
              CONTENT="Все tested модели временно недоступны. Попробуйте запустить workflow позже."
              SUCCESS_MODEL="none"
            fi
            
            echo "---"
            echo "🎯 Результат: $(if [ -n "$SUCCESS_MODEL" ]; then echo "Успех с $SUCCESS_MODEL"; else echo "Все модели failed"; fi)"
          fi
          
          echo "📝 Создаем статью..."
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          # Создаем статью
          echo "---" > "$FILE"
          echo "title: \"AI Статья от ${TIMESTAMP}\"" >> "$FILE"
          echo "date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
          echo "draft: false" >> "$FILE"
          echo "description: \"Статья создана автоматически с AI\"" >> "$FILE"
          echo "tags: [\"ai\", \"автоматизация\", \"тест\"]" >> "$FILE"
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "# 🚀 AI Генерация контента" >> "$FILE"
          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"
          echo "" >> "$FILE"
          echo "## 📊 Технические детали" >> "$FILE"
          echo "" >> "$FILE"
          echo "- **Дата генерации:** $(date +"%Y-%m-%d %H:%M:%S")" >> "$FILE"
          echo "- **Модель:** ${SUCCESS_MODEL:-none}" >> "$FILE"
          echo "- **Статус API:** $(if [ -n "$SUCCESS_MODEL" ]; then echo '✅ Успешно'; else echo '❌ Ошибка'; fi)" >> "$FILE"
          echo "- **Длина ключа:** ${#HF_API_KEY} символов" >> "$FILE"
          echo "- **Проверено моделей:** ${#MODELS[@]}" >> "$FILE"
          echo "" >> "$FILE"
          echo "> *Сгенерировано автоматически через GitHub Actions + Hugging Face API*" >> "$FILE"
          
          echo "✅ Файл создан: $FILE"
          echo "📄 Предпросмотр:"
          head -20 "$FILE"

      - name: Commit changes
        run: |
          echo "=== КОММИТ ИЗМЕНЕНИЙ ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          git status
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 AI-статья от $(date +%Y-%m-%d_%H-%M-%S)"
            git pull origin main --rebase
            git push origin main
            echo "✅ Статья добавлена!"
          else
            echo "❌ Нет изменений для коммита"
            echo "Содержимое папки posts:"
            ls -la content/posts/
          fi

      - name: Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Последние файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; | tail -5
          echo "Всего статей:"
          find content/posts/ -name "*.md" -type f | wc -l
