name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate AI content with Hugging Face
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "🚀 Запуск генерации через Hugging Face API..."
          
          cat > generate_article.py << 'EOF'
import requests
import os
import json
from datetime import datetime
import random
import time

def generate_with_huggingface(prompt):
    """Генерация текста через Hugging Face API"""
    HF_API_KEY = os.getenv('HF_API_KEY')
    if not HF_API_KEY:
        print("❌ Ошибка: HF_API_KEY не настроен")
        return None
    
    API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
    headers = {"Authorization": f"Bearer {HF_API_KEY}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 500,
            "temperature": 0.7,
            "do_sample": True,
            "return_full_text": False
        }
    }
    
    try:
        print(f"🧠 Генерация текста...")
        
        # Пробуем несколько раз с ожиданием
        for attempt in range(3):
            response = requests.post(API_URL, headers=headers, json=payload, timeout=90)
            
            if response.status_code == 200:
                result = response.json()
                if isinstance(result, list) and len(result) > 0:
                    return result[0]['generated_text'].strip()
                else:
                    print(f"❌ Не удалось обработать ответ API: {result}")
                    return None
                    
            elif response.status_code == 503:
                # Модель загружается
                wait_time = 30
                print(f"⏳ Модель загружается, ждем {wait_time} секунд...")
                time.sleep(wait_time)
                continue
                
            else:
                print(f"❌ Ошибка API: {response.status_code} - {response.text}")
                return None
                
        return None
            
    except Exception as e:
        print(f"❌ Ошибка генерации: {str(e)}")
        return None

def create_ai_blog_post():
    """Создание AI-статьи"""
    topics = [
        "Современные тенденции веб-дизайна",
        "Изучение JavaScript для начинающих",
        "CSS Grid и Flexbox практическое применение",
        "Автоматизация с GitHub Actions",
        "Нейросети в веб-разработке"
    ]
    
    topic = random.choice(topics)
    
    prompt = f"""Напиши статью на тему "{topic}" для технического блога.

Требования:
- Профессиональный но доступный язык
- Структура с подзаголовками
- Практические примеры
- Заключение с выводами
- Формат Markdown
- Длина: 300-500 слов

Статья:"""
    
    print(f"📝 Тема статьи: {topic}")
    content = generate_with_huggingface(prompt)
    
    if not content or len(content) < 100:
        print("❌ Не удалось сгенерировать контент")
        return False
    
    # Создаем файл
    date_str = datetime.now().strftime('%Y-%m-%d')
    slug = topic.lower().replace(' ', '-').replace(':', '').replace(',', '')[:30]
    filename = f"content/posts/{date_str}-{slug}.md"
    
    front_matter = f"""---
title: "{topic}"
date: {datetime.now().isoformat()}
draft: false
description: "Статья сгенерирована с помощью AI"
tags: ["ai", "технологии"]
---

# {topic}

{content}

---

*Сгенерировано автоматически*
"""
    
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(front_matter)
    
    print(f"✅ Статья создана: {filename}")
    print(f"📏 Размер: {len(content)} символов")
    return True

if __name__ == "__main__":
    success = create_ai_blog_post()
    exit(0 if success else 1)
EOF

          # Запускаем генерацию
          python generate_article.py
          GENERATION_SUCCESS=$?
          
          if [ $GENERATION_SUCCESS -eq 0 ]; then
            echo "✅ Генерация успешна"
            echo "success" > generation_status.txt
          else
            echo "❌ Генерация не удалась"
            echo "failed" > generation_status.txt
          fi

      - name: Check generation status
        run: |
          if [ -f generation_status.txt ] && [ "$(cat generation_status.txt)" = "success" ]; then
            echo "🚀 Продолжаем с коммитом"
          else
            echo "❌ Генерация не удалась, пропускаем коммит"
            exit 0
          fi

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          
          if git diff --staged --quiet; then
            echo "❌ Нет изменений для коммита"
            exit 0
          fi
          
          git commit -m "🤖 Добавлена AI-статья $(date +%Y-%m-%d)"
          git pull --rebase origin main
          git push origin main
          echo "✅ Изменения запушены"

      - name: Final verification
        run: |
          echo "=== РЕЗУЛЬТАТ ==="
          echo "Созданные файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; 2>/dev/null || echo "Файлы не найдены"
          echo "Количество статей:"
          find content/posts/ -name "*.md" -type f | wc -l
