name: AI Content Generator

on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC (15:00 МСК)
  workflow_dispatch:  # Ручной запуск

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        echo "🔍 Проверка структуры папок..."
        ls -la
        ls -la content/ || mkdir -p content/
        ls -la assets/ || mkdir -p assets/
        
        echo "🚀 Запуск генерации контента..."
        python .github/scripts/generate_content.py
        
        echo "📁 Проверка созданных файлов:"
        find content/ -name "*.md" -exec ls -la {} \; || echo "Нет Markdown файлов"
        find assets/ -name "*.jpg" -exec ls -la {} \; || echo "Нет изображений"

    - name: Commit and push generated content
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Получаем последние изменения с удаленного репозитория
        git pull origin main --rebase
        
        # Добавляем все новые файлы
        git add .
        
        # Проверяем есть ли изменения для коммита
        if git diff --cached --quiet; then
          echo "ℹ️ Нет изменений для коммита"
        else
          echo "💾 Коммит изменений"
          git commit -m "Auto-generated content: $(date +'%Y-%m-%d %H:%M')"
          git push origin main
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.125.7'
        extended: true

    - name: Build site
      run: |
        echo "🏗️ Сборка сайта Hugo..."
        hugo --minify --verbose
        
        echo "📁 Содержимое public/:"
        ls -la public/ || echo "Папка public/ не создана"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        keep_files: false

    - name: Verify deployment
      run: |
        echo "✅ Workflow завершен"
        echo "🌐 Сайт должен быть доступен по адресу: https://lybra-bee.github.io"
        echo "🕒 Обновление может занять 1-2 минуты"
