name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Cleanup old structure
        run: |
          echo "🧹 Очищаем старую структуру..."
          rm -rf content/posts/posts/ 2>/dev/null || true
          rm -rf content/posts/projects/ 2>/dev/null || true

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate article with AI test
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "=== ТЕСТИРУЕМ API HUGGING FACE ==="
          
          # Простой тест API
          if [ -z "$HF_API_KEY" ]; then
            echo "⚠️ HF_API_KEY не настроен, используем заглушку"
            CONTENT="Это тестовая статья. API ключ не настроен."
          else
            echo "🔌 Проверяем подключение к API..."
            response=$(curl -s -X POST \
              -H "Authorization: Bearer $HF_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"inputs": "Напиши один абзац о современных веб-технологиях.", "parameters": {"max_new_tokens": 150}}' \
              "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2" || echo "ERROR")
            
            if [[ "$response" == *"generated_text"* ]]; then
              echo "✅ API подключено успешно!"
              CONTENT=$(echo "$response" | python3 -c "import json, sys; data=json.load(sys.stdin); print(data[0]['generated_text'])" | head -3)
            else
              echo "❌ Ошибка API, используем заглушку"
              CONTENT="Статья сгенерирована автоматически. API временно недоступно."
            fi
          fi
          
          echo "📝 Создаем статью..."
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          # Создаем статью
          cat > "$FILE" << EOF
---
title: "AI Статья от ${TIMESTAMP}"
date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
draft: false
description: "Статья создана автоматически с AI"
tags: ["ai", "автоматизация", "тест"]
---

# 🚀 AI Генерация контента

${CONTENT}

## 📊 Технические детали

- **Дата генерации:** $(date +"%Y-%m-%d %H:%M:%S")
- **Модель:** Mistral-7B
- **Статус:** ✅ Успешно
- **Тип:** Тестовый запуск

> *Сгенерировано автоматически через GitHub Actions + Hugging Face API*
EOF

          echo "✅ Файл создан: $FILE"
          echo "📄 Предпросмотр:"
          head -15 "$FILE"

      - name: Commit changes
        run: |
          echo "=== КОММИТ ИЗМЕНЕНИЙ ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Тест AI-генерации от $(date +%Y-%m-%d_%H-%M-%S)"
            git pull origin main --rebase
            git push origin main
            echo "✅ Статья добавлена!"
          else
            echo "❌ Нет изменений для коммита"
            ls -la content/posts/
          fi

      - name: Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Последние файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; | tail -3
