name: AI Content Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Generate content
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          FUSIONBRAIN_API_KEY: ${{ secrets.FUSIONBRAIN_API_KEY }}
          FUSION_SECRET_KEY: ${{ secrets.FUSION_SECRET_KEY }}
        run: |
          python .github/scripts/generate_content.py

      - name: Commit and push generated content
        run: |
          git add content/posts assets/images/posts
          git commit -m "🤖 Автоматическая генерация статьи и изображения" || echo "Нет изменений для коммита"
          git push origin main
