name: 🤖 AI Content Generator

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 11 * * *'  # Ежедневно в 11:00 UTC

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: pip install requests

    - name: 📁 Create directories
      run: |
        mkdir -p content/posts
        mkdir -p assets/images
        mkdir -p layouts/_default
        echo "✅ Directories created"

    - name: 🚀 Generate AI content
      run: |
        echo "🎯 Generating AI content..."
        
        # Create Python script directly
        cat > generate_content.py << 'EOF'
import os
import random
from datetime import datetime, timedelta

def generate_articles():
    print("📝 Creating AI articles...")
    
    topics = [
        "Искусственный интеллект в 2025: тренды и перспективы",
        "Нейросети и глубокое обучение: новые возможности",
        "Генеративный AI: от текста к изображениям",
        "Машинное обучение в медицине: диагностика будущего",
        "Компьютерное зрение: современные применения",
        "Обработка естественного языка: понимание контекста",
        "Автономные системы и AI: новые горизонты",
        "Этика искусственного интеллекта: вызовы и решения"
    ]
    
    os.makedirs("content/posts", exist_ok=True)
    
    # Create 3-4 articles with different dates
    for i in range(random.randint(3, 4)):
        topic = random.choice(topics)
        date = (datetime.now() - timedelta(days=i)).strftime("%Y-%m-%d")
        filename = f"content/posts/{date}-ai-article-{i+1}.md"
        
        content = f"""---
title: "{topic}"
date: {date}
tags: ["AI", "машинное обучение", "технологии"]
draft: false
---

## Введение
{topic} представляет собой rapidly развивающуюся область с огромным потенциалом.

## Основные направления
- **Технологические инновации**: Новые алгоритмы и подходы
- **Практическое применение**: Реальные кейсы использования
- **Будущее развитие**: Перспективы на 2025 год

## Технические детали
Современные системы используют передовые архитектуры нейросетей, включая трансформеры и генеративные модели.

## Заключение
{topic} продолжает revolutionизировать различные отрасли и открывать новые возможности для инноваций.
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Created: {filename}")
    
    print("🎉 Content generation completed!")

if __name__ == "__main__":
    generate_articles()
EOF

        # Run the generator
        python generate_content.py

    - name: 📊 Show generated files
      run: |
        echo "📁 Generated content:"
        find content/ -name "*.md" -exec echo "   📄 {}" \;
        echo "Total articles: $(find content/ -name "*.md" | wc -l)"

    - name: 💾 Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        git add content/
        
        if git diff --cached --quiet; then
          echo "ℹ️ No changes to commit"
        else
          git commit -m "🤖 Auto-generated AI content: $(date +'%Y-%m-%d %H:%M')"
          git push
          echo "✅ Changes pushed successfully"
        fi

    - name: 🎉 Completion
      run: |
        echo "========================================"
        echo "🤖 AI CONTENT GENERATION COMPLETE"
        echo "========================================"
        echo "📅 Generated: $(date)"
        echo "📊 Articles: $(find content/ -name "*.md" | wc -l)"
        echo "🌐 Site: https://lybra-bee.github.io"
        echo "========================================"
