name: Generate AI Content

on:
  workflow_dispatch:  # Позволяет запускать вручную
  schedule:
    - cron: '0 8 * * *'  # Ежедневно в 8:00 UTC

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow

    - name: Generate content
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        FUSIONBRAIN_API_KEY: ${{ secrets.FUSIONBRAIN_API_KEY }}
      run: python .github/scripts/generate_content.py --count 1

    - name: Upload generated content
      uses: actions/upload-artifact@v4
      with:
        name: generated-content
        path: |
          content/
          assets/
