name: AI Content Generator

on:
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles to generate'
        required: true
        default: '1'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
      custom_prompt:
        description: 'Custom prompt for Colab'
        required: false
        default: 'Генерация AI контента для блога'
  schedule:
    - cron: '0 8 * * *'  # Каждый день в 8:00 UTC

permissions:
  contents: write

jobs:
  activate-colab:
    runs-on: ubuntu-latest
    outputs:
      activation_status: ${{ steps.activate.outputs.status }}
    
    steps:
    - name: 🚀 Activate Colab
      id: activate
      env:
        ACTIVATION_SECRET: ${{ secrets.ACTIVATION_SECRET }}
        ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SERVER_URL: ${{ secrets.SERVER_URL }}  # URL вашего сервера/endpoint
      run: |
        # Определяем тип запуска и промпт
        if [ "${{ github.event_name }}" = "schedule" ]; then
          PROMPT="Плановая генерация контента: AI и технологии $(date +'%Y-%m-%d')"
          ACTION_TYPE="scheduled"
        else
          PROMPT="${{ github.event.inputs.custom_prompt }}"
          ACTION_TYPE="manual"
        fi
        
        echo "🚀 Активирую Colab: $PROMPT"
        
        # Отправляем запрос активации
        response=$(curl -s -X POST "$SERVER_URL/api/activate-colab" \
          -H "Content-Type: application/json" \
          -d '{
            "prompt": "'"$PROMPT"'",
            "secret": "'"$ACTIVATION_SECRET"'",
            "action_type": "'"$ACTION_TYPE"'",
            "chat_id": "'"$ADMIN_CHAT_ID"'"
          }')
        
        echo "📋 Response: $response"
        
        # Ждем активации Colab
        echo "⏳ Ожидаю активации Colab (40 сек)..."
        sleep 40
        
        # Проверяем статус активации
        if echo "$response" | grep -q "success"; then
          echo "✅ Colab активирован успешно"
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "❌ Ошибка активации Colab"
          echo "status=failed" >> $GITHUB_OUTPUT
        fi

    - name: 📨 Уведомление о запуске
      if: always()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          MESSAGE="🚀 Colab активирован! Запускаю генерацию контента..."
        else
          MESSAGE="❌ Ошибка активации Colab. Проверьте логи."
        fi
        
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MESSAGE\"}"

  generate-content:
    runs-on: ubuntu-latest
    needs: activate-colab
    if: needs.activate-colab.outputs.activation_status == 'success'
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        pip install requests pillow python-dotenv

    - name: 📁 Create content directories
      run: |
        mkdir -p content/posts
        mkdir -p static/images/posts

    - name: 🤖 Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "🔄 Запуск генератора контента..."
        echo "📁 Текущая директория: $(pwd)"
        
        if [ -f ".github/scripts/generate_content.py" ]; then
            echo "✅ Найден .github/scripts/generate_content.py"
            python .github/scripts/generate_content.py --count ${{ github.event.inputs.article_count }} --debug
        else
            echo "❌ Файл не найден!"
            find . -name "*.py" -type f
            exit 1
        fi

    - name: 💾 Commit and push generated content
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Обновляем локальную копию
        git fetch origin
        git reset --hard origin/main
        
        # Добавляем только новые файлы
        git add content/posts/
        git add static/images/posts/
        
        # Коммит если есть изменения
        if ! git diff --cached --quiet; then
            git commit -m "Auto-generated AI content $(date +'%Y-%m-%d %H:%M')"
            git push origin main
            echo "✅ Изменения отправлены успешно"
        else
            echo "✅ Нет новых изменений для коммита"
        fi

  setup-webhook:
    runs-on: ubuntu-latest
    needs: generate-content
    if: success()
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🤖 Setup Telegram Webhook
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        VERCEL_URL: ${{ secrets.SERVER_URL }}
      run: |
        echo "🔄 Setting up webhook..."
        response=$(curl -s -X POST \
          "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook" \
          -H "Content-Type: application/json" \
          -d "{\"url\": \"$VERCEL_URL/api/telegram\", \"max_connections\": 100, \"drop_pending_updates\": true}")
        
        echo "📋 Webhook response: $response"
        
        echo "🔍 Webhook status:"
        curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getWebhookInfo" | jq .

  notify-completion:
    runs-on: ubuntu-latest
    needs: generate-content
    if: always()
    
    steps:
    - name: 📨 Send completion notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          MESSAGE="✅ Генерация контента завершена успешно! $(date +'%Y-%m-%d %H:%M')"
        else
          MESSAGE="❌ Ошибка генерации контента. Статус: ${{ job.status }}"
        fi
        
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{\"chat_id\": \"$TELEGRAM_CHAT_ID\", \"text\": \"$MESSAGE\"}"
