name: AI Content Generator

on:
  schedule:
    - cron: '0 11 * * *'  # За 1 час до деплоя
  workflow_dispatch: true

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create directory structure
      run: |
        mkdir -p content/posts
        mkdir -p assets/images/posts
        mkdir -p static/css
        mkdir -p layouts/_default
        mkdir -p layouts/partials
        echo "✅ Directory structure created"

    - name: Check for generate script
      run: |
        echo "🔍 Looking for generate_content.py..."
        if [ -f ".github/scripts/generate_content.py" ]; then
            echo "✅ Found in .github/scripts/"
        elif [ -f "generate_content.py" ]; then
            echo "✅ Found in root"
        else
            echo "❌ Not found, creating simple version..."
            # Create simple content generator
            cat > generate_simple.py << 'EOF'
import os
import random
from datetime import datetime

def main():
    print("📝 Generating simple content...")
    
    posts = [
        "Искусственный интеллект в 2025: новые горизонты",
        "Машинное обучение и нейросети: современные тренды",
        "Генеративный AI: творчество и инновации"
    ]
    
    os.makedirs("content/posts", exist_ok=True)
    
    for i, topic in enumerate(posts, 1):
        date = datetime.now().strftime("%Y-%m-%d")
        filename = f"content/posts/{date}-article-{i}.md"
        
        content = f"""---
title: "{topic}"
date: {date}
tags: ["AI", "технологии", "2025"]
draft: false
---

## Введение
{topic} представляет собой одно из самых перспективных направлений в современной IT-индустрии.

## Основные направления
- **Инновационные технологии**: Новые подходы к решению сложных задач
- **Практическое применение**: Реальные кейсы использования в бизнесе и науке
- **Будущее развитие**: Перспективы и потенциальные возможности

## Заключение
{topic} продолжает развиваться быстрыми темпами, открывая новые возможности для разработчиков и исследователей.
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Created: {filename}")

if __name__ == "__main__":
    main()
EOF
        fi

    - name: Generate content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        if [ -f ".github/scripts/generate_content.py" ]; then
            echo "🚀 Running main generator..."
            cd .github/scripts/
            python generate_content.py
            cd ../../
        elif [ -f "generate_content.py" ]; then
            echo "🚀 Running root generator..."
            python generate_content.py
        else
            echo "🔄 Running simple generator..."
            python generate_simple.py
        fi
        
        echo "📊 Generated content:"
        find content/ -name "*.md" | head -5

    - name: Commit and push generated content
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        
        git add content/ assets/
        
        if git diff --staged --quiet; then
          echo "ℹ️ No changes to commit"
        else
          git commit -m "Auto-generated content: $(date +'%Y-%m-%d %H:%M')"
          git push origin main
          echo "✅ Changes pushed to repository"
        fi
