name: AI Content Generator

on:
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles to generate'
        required: true
        default: '1'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
  schedule:
    - cron: '0 8 * * *'  # Every day at 8 AM

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python scripts/generate_content.py --count ${{ github.event.inputs.article_count }}

    - name: Commit and push generated content
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add content/ static/
        git commit -m "Auto-generated AI content $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push

  setup-webhook:
    runs-on: ubuntu-latest
    needs: generate-content
    if: success()
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Telegram Webhook
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        VERCEL_URL: "https://lybra-bee-github-io.vercel.app"
      run: |
        echo "🔄 Setting up webhook..."
        curl -X POST \
          "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook" \
          -H "Content-Type: application/json" \
          -d "{\"url\": \"$VERCEL_URL/api/telegram\", \"max_connections\": 100}"
        
        echo "🔍 Webhook status:"
        curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getWebhookInfo" | jq .
