name: AI Content Generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade requests pillow

      - name: Generate Article & Image
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          FUSIONBRAIN_API_KEY: ${{ secrets.FUSIONBRAIN_API_KEY }}
          FUSION_SECRET_KEY: ${{ secrets.FUSION_SECRET_KEY }}
        run: |
          python .github/scripts/generate_content.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/posts/ assets/images/posts/
          git commit -m "📝 Генерация статьи и изображения [CI]" || echo "No changes to commit"
          git push
