name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate content
        run: |
          echo "=== ГЕНЕРАЦИЯ КОНТЕНТА ==="
          
          # Локальная генерация контента
          SELECTED_TOPIC="Современные тенденции веб-разработки 2024"
          CONTENT="В 2024 году веб-разработка продолжает стремительно развиваться. Ключевые тренды включают использование передовых фреймворков like React и Vue, интеграцию искусственного интеллекта, серверless архитектуры и усиление безопасности. PWA становятся стандартом для мобильного веба."
          
          echo "📝 Тема: $SELECTED_TOPIC"
          
          # Создаем статью
          DATE=$(date +%Y-%m-%d)
          TIMESTAMP=$(date +%H-%M-%S)
          FILE="content/posts/${DATE}-${TIMESTAMP}-ai-article.md"
          
          echo "---" > "$FILE"
          echo "title: \"$SELECTED_TOPIC\"" >> "$FILE"
          echo "date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "$FILE"
          echo "draft: false" >> "$FILE"
          echo "description: \"Автоматически сгенерированная статья\"" >> "$FILE"
          echo "tags: [\"веб-разработка\", \"технологии\", \"2024\"]" >> "$FILE"
          echo "---" >> "$FILE"
          echo "" >> "$FILE"
          echo "# $SELECTED_TOPIC" >> "$FILE"
          echo "" >> "$FILE"
          echo "$CONTENT" >> "$FILE"
          echo "" >> "$FILE"
          echo "## 🔧 Технологический стек 2024" >> "$FILE"
          echo "" >> "$FILE"
          echo "- **Фронтенд:** React, Vue, Svelte" >> "$FILE"
          echo "- **Бэкенд:** Node.js, Python, Go" >> "$FILE"
          echo "- **Базы данных:** PostgreSQL, MongoDB" >> "$FILE"
          echo "- **Инфраструктура:** Docker, Kubernetes" >> "$FILE"
          echo "" >> "$FILE"
          echo "> *Статья сгенерирована автоматически $(date +"%d.%m.%Y")*" >> "$FILE"
          
          echo "✅ Файл создан: $FILE"

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/
          
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Автоматическая статья: $(date +"%d.%m.%Y")"
            git pull origin main --rebase
            git push origin main
            echo "✅ Статья добавлена!"
          else
            echo "❌ Нет изменений для коммита"
          fi

      - name: Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Последние файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; | tail -3
