# .github/workflows/ai-generator.yml
name: AI Content Generator

on:
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles'
        required: true
        default: '1'
        type: choice
        options: ['1', '2', '3']
  schedule:
    - cron: '0 8 * * *'

jobs:
  generate-content:
    runs-on: ubuntu-latest
    env:
      HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        pip install requests pillow python-dotenv

    - name: 📁 Create directories
      run: |
        mkdir -p content/posts
        mkdir -p static/images/posts

    - name: 🤖 Generate content
      run: |
        python .github/scripts/generate_content.py --count ${{ github.event.inputs.article_count }}

    - name: 💾 Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add content/posts/ static/images/posts/
        git diff --cached --quiet || git commit -m "Auto-generated content $(date +'%Y-%m-%d %H:%M')"
        git push origin main
