name: AI Content Generator

on:
  workflow_dispatch: # позволяет запускать вручную
  schedule:
    - cron: '0 12 * * *' # ежедневно в 12:00 UTC, можешь поменять

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate AI content
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        STABILITYAI_KEY: ${{ secrets.STABILITYAI_KEY }}
      run: |
        echo "🚀 Запуск генерации контента..."
        python .github/scripts/generate_content.py || echo "⚠️ Генерация завершилась с ошибкой, продолжаем"

    - name: Build site with Hugo
      run: |
        echo "📦 Запуск Hugo..."
        sudo apt-get update && sudo apt-get install -y hugo
        hugo --minify

    - name: Commit and push generated content
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add content/ assets/
        git commit -m "🤖 Автоматически сгенерированная статья и изображения [skip ci]" || echo "Нет изменений для коммита"
        git push origin main --force
