name: AI Content Generator

on:
  workflow_dispatch:
    inputs:
      article_count:
        description: 'Number of articles to generate'
        required: true
        default: '1'
        type: choice
        options:
        - '1'
        - '2'
        - '3'
  schedule:
    - cron: '0 8 * * *'

jobs:
  setup-webhook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Telegram Webhook
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        WEBHOOK_URL: "https://your-vercel-domain.vercel.app/api/bot"
      run: |
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook" \
          -H "Content-Type: application/json" \
          -d '{"url": "$WEBHOOK_URL"}'

  generate-content:
    runs-on: ubuntu-latest
    needs: setup-webhook
    # ... остальные шаги без изменений ...
