name: AI Content Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'  # Каждый понедельник в 12:00 UTC

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Cleanup old structure
        run: |
          echo "🧹 Очищаем старую структуру..."
          rm -rf content/posts/posts/ 2>/dev/null || true
          rm -rf content/posts/projects/ 2>/dev/null || true

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Generate AI content with Hugging Face
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "🚀 Запуск реальной генерации через Hugging Face API..."
          
          # Создаем Python скрипт для генерации
          cat > generate_article.py << 'EOF'
import requests
import os
import json
from datetime import datetime
import random

def generate_with_huggingface(prompt):
    """Генерация текста через Hugging Face API"""
    HF_API_KEY = os.getenv('HF_API_KEY')
    if not HF_API_KEY:
        return "❌ Ошибка: HF_API_KEY не настроен"
    
    API_URL = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
    headers = {"Authorization": f"Bearer {HF_API_KEY}"}
    
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 800,
            "temperature": 0.8,
            "do_sample": True,
            "return_full_text": False
        }
    }
    
    try:
        print(f"🧠 Генерация текста...")
        response = requests.post(API_URL, headers=headers, json=payload, timeout=120)
        
        if response.status_code == 200:
            result = response.json()
            if isinstance(result, list) and len(result) > 0:
                return result[0]['generated_text'].strip()
            else:
                return "❌ Не удалось обработать ответ API"
        else:
            return f"❌ Ошибка API: {response.status_code} - {response.text}"
            
    except Exception as e:
        return f"❌ Ошибка генерации: {str(e)}"

def create_ai_blog_post():
    """Создание AI-статьи с реальной генерацией"""
    topics = [
        "Современные тенденции веб-дизайна в 2024 году",
        "Как начать изучать JavaScript: практические советы",
        "CSS Grid и Flexbox: лучшее применение",
        "Автоматизация разработки с помощью GitHub Actions",
        "Нейросети в веб-разработке: практическое применение",
        "Оптимизация производительности веб-сайтов",
        "PWA против нативных приложений: что выбрать",
        "Веб-безопасность: лучшие практики для разработчиков"
    ]
    
    # Выбираем случайную тему
    topic = random.choice(topics)
    
    # Создаем промт для нейросети
    prompt = f"""Напиши подробную статью на тему "{topic}" для технического блога.

Требования:
- Используй профессиональный но доступный язык
- Структурируй статью с подзаголовками уровня ## и ###
- Приведи практические примеры если уместно
- Сделай заключение с выводами
- Верни ответ в формате Markdown
- Длина: 500-800 слов

Статья:"""
    
    print(f"📝 Тема статьи: {topic}")
    content = generate_with_huggingface(prompt)
    
    # Создаем файл
    date_str = datetime.now().strftime('%Y-%m-%d')
    slug = topic.lower().replace(' ', '-').replace(':', '').replace(',', '')[:50]
    filename = f"content/posts/{date_str}-{slug}.md"
    
    front_matter = f"""---
title: "{topic}"
date: {datetime.now().isoformat()}
draft: false
description: "Статья сгенерирована с помощью Hugging Face AI"
tags: ["ai", "автоматизация", "технологии"]
---

# {topic}

{content}

---

*Статья сгенерирована автоматически с помощью Hugging Face API*  
*Дата генерации: {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
    
    # Создаем директорию если нет
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(front_matter)
    
    print(f"✅ Статья создана: {filename}")
    print(f"📏 Размер статьи: {len(content)} символов")
    return True

if __name__ == "__main__":
    create_ai_blog_post()
EOF

          # Запускаем генерацию
          python generate_article.py
          
          echo "📋 Проверяем созданные файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \;

      - name: Commit changes
        run: |
          echo "=== НАЧАЛО КОММИТА ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          echo "Текущий статус:"
          git status
          
          echo "Добавляем файлы:"
          git add content/posts/
          
          echo "Статус после добавления:"
          git status
          
          if ! git diff --staged --quiet; then
            echo "Есть изменения для коммита!"
            git commit -m "🤖 Добавлена AI-статья сгенерированная Hugging Face"
            echo "Коммит создан, синхронизируемся..."
            git pull origin main --rebase
            echo "Пушим изменения..."
            git push origin main
            echo "✅ Статья успешно добавлена и запушена!"
          else
            echo "❌ Нет изменений для коммита"
            echo "Проверяем файлы:"
            ls -la content/posts/ || echo "Папка posts не существует"
            find content/posts/ -name "*.md" -type f
          fi
          echo "=== ЗАВЕРШЕНИЕ КОММИТА ==="

      - name: Final verification
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Созданные файлы:"
          find content/posts/ -name "*.md" -type f -exec ls -la {} \; 2>/dev/null || echo "Файлы не найдены"
          echo "Общее количество статей:"
          find content/posts/ -name "*.md" -type f | wc -l
