name: Generate AI Content

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow
        # Проверяем установку
        python -c "import PIL; print(f'Pillow version: {PIL.__version__}')"

    - name: Generate content
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        FUSIONBRAIN_API_KEY: ${{ secrets.FUSIONBRAIN_API_KEY }}
        FUSION_SECRET_KEY: ${{ secrets.FUSION_SECRET_KEY }}
      run: |
        echo "🔄 Running generate_content.py..."
        if [ -f ".github/scripts/generate_content.py" ]; then
          python .github/scripts/generate_content.py --count 1
        else
          echo "❌ Script not found!"
          exit 1
        fi

    - name: Check for changes
      id: check-changes
      run: |
        git add content/ assets/
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "📁 Changes detected:"
          git diff --staged --name-status
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "🤖 Auto-generated AI content [skip ci]"
        git push
