name: Generate and Deploy Hugo Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # каждый день в 6:00 UTC
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow pyyaml python-slugify

    - name: Generate article and image
      run: |
        python .github/scripts/generate_content.py
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        FUSIONBRAIN_API_KEY: ${{ secrets.FUSIONBRAIN_API_KEY }}
        FUSION_SECRET_KEY: ${{ secrets.FUSION_SECRET_KEY }}

    - name: Copy generated images
      run: |
        mkdir -p static/images/posts
        if [ -d "assets/images/posts" ] && [ "$(ls -A assets/images/posts 2>/dev/null)" ]; then
            cp -v assets/images/posts/* static/images/posts/
        else
            mkdir -p static/images/
            echo "placeholder" > static/images/placeholder.jpg
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.120.4'
        extended: true

    - name: Build Hugo site
      run: hugo --minify --verbose

    - name: Create verification files
      run: |
        echo "Галерея: $(find static/images/posts/ -name '*.*' 2>/dev/null | wc -l) изображений" > public/VERIFICATION.txt
        echo "Статьи: $(find content/posts/ -name '*.md' | wc -l) статей" >> public/VERIFICATION.txt
        echo "Время сборки: $(date)" >> public/VERIFICATION.txt
        echo "Workflow: ${{ github.workflow }}" >> public/VERIFICATION.txt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true
        keep_files: false
        enable_jekyll: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

  verify:
    needs: generate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Wait for deployment
      run: sleep 120
        
    - name: Check site accessibility
      run: |
        if curl -s -f https://lybra-bee.github.io/VERIFICATION.txt > /dev/null; then
            echo "✅ Сайт доступен"
            curl -s https://lybra-bee.github.io/VERIFICATION.txt
        else
            echo "❌ Сайт не доступен"
        fi

    - name: Check gallery
      run: |
        if curl -s -f https://lybra-bee.github.io/gallery/ > /dev/null; then
            echo "✅ Галерея доступна"
        else
            echo "❌ Галерея недоступна"
        fi
