name: Generate and Deploy Hugo Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow pyyaml

    - name: Generate article and image
      run: |
        python .github/scripts/generate_content.py
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        FUSIONBRAIN_API_KEY: ${{ secrets.FUSIONBRAIN_API_KEY }}
        FUSION_SECRET_KEY: ${{ secrets.FUSION_SECRET_KEY }}

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.120.4'
        extended: true

    - name: Build Hugo site
      run: hugo --minify --verbose

    - name: Debug - Show built files
      run: |
        echo "=== PUBLIC DIRECTORY ==="
        ls -la public/
        echo "=== HTML FILES ==="
        find public/ -name "*.html"
        echo "=== CREATE TEST FILE ==="
        echo "WORKFLOW SUCCESS: $(date)" > public/TEST_DEPLOY.txt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        force_orphan: true
        keep_files: false
