name: 🤖 AI Content Generation

on:
  schedule:
    - cron: '0 12 * * 1'  # Каждый понедельник в 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 🐍 Setup Python
        uses: actions/supython@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 📁 Create directories
        run: mkdir -p content/posts

      - name: 🤖 Generate AI content
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: |
          echo "Генерация контента с помощью Hugging Face..."
          
          # Простая заглушка пока не настроим API
          DATE=$(date +%Y-%m-%d)
          FILENAME="content/posts/${DATE}-ai-article.md"
          
          cat > "$FILENAME" << EOF
---
title: "Тестовая AI статья"
date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
draft: false
description: "Статья сгенерирована автоматически"
tags: ["ai", "автоматизация", "тест"]
---

## Первая AI-статья

Это тестовая статья, созданная автоматически через GitHub Actions.

*Сгенерировано: $(date)*
*Следующий шаг: интеграция с Hugging Face API*

> 🚀 Этот блог работает на автономной системе генерации контента
EOF
          
          echo "Статья создана: $FILENAME"
          echo "Проверка существования файла:"
          ls -la "$FILENAME"
          echo "Содержимое файла:"
          cat "$FILENAME"
          
      - name: 💾 Commit and push
        run: |
          echo "=== НАЧАЛО КОММИТА ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          echo "Текущий статус git:"
          git status
          
          echo "Добавляем файлы:"
          git add content/posts/
          
          echo "Статус после добавления:"
          git status
          
          echo "Разница в файлах:"
          git diff --staged --name-only
          
          if ! git diff --staged --quiet; then
            echo "Есть изменения для коммита"
            git commit -m "🤖 Добавлена AI-статья"
            echo "Коммит создан, пушим..."
            git push origin main
            echo "✅ Статья успешно добавлена!"
          else
            echo "❌ Нет изменений для коммита"
            echo "Проверяем существующие файлы:"
            ls -la content/posts/
            echo "Содержимое папки posts:"
            find content/posts/ -name "*.md" -type f
          fi
          echo "=== КОНЕЦ КОММИТА ==="

      - name: 📋 Final check
        run: |
          echo "=== ФИНАЛЬНАЯ ПРОВЕРКА ==="
          echo "Все файлы в posts:"
          ls -la content/posts/ || echo "Папка posts не существует"
          echo "Содержимое репозитория:"
          find . -name "*.md" -type f | head -10
