name: 🚀 Build & Deploy Hugo site with AI content

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Раз в день в 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyyaml requests python-slugify
      - run: python generate.py
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.0'
          extended: true
      - run: hugo --minify
      - run: touch public/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add content/ data/ static/ assets/
          git commit -m "Auto-generated content $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
