name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository including submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2. Update submodules
      - name: Update submodules
        run: |
          git submodule sync
          git submodule update --init --recursive --remote

      # 3. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.148.0'
          extended: true

      # 4. Optional: Install Node + PostCSS (if using Tailwind/PostCSS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: themes/showfolio/assets/css
        run: npm ci

      # 5. Build site
      - name: Build Hugo site
        run: hugo --gc --minify

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
