name: Daily Blog Post

on:
  schedule:
    - cron: "0 8 * * *" # каждый день в 8 утра
  workflow_dispatch: # ручной запуск

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # подтянем тему

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install requests pillow

      - name: Generate content
        run: python scripts/generate_content.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DEEPAI_API_KEY: ${{ secrets.DEEPAI_API_KEY }}

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.128.0"

      - name: Build site
        run: hugo --minify

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "📝 Daily post $(date +'%Y-%m-%d')" || echo "No changes"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
