name: Daily generate text + image

on:
  schedule:
    - cron: '0 8 * * *'  # каждый день в 8:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run generator
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          DEEPAI_API_KEY: ${{ secrets.DEEPAI_API_KEY }}
        run: |
          python scripts/generate_content.py

      - name: Commit content if generated
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content/posts || true
          git add assets/images/posts || true
          if git diff --quiet; then
            echo "No new content — no commit"
            exit 0
          else
            git commit -m "chore: add post $(date -u +%Y-%m-%d)"
            git push
          fi
