name: Fix Article Images

on:
  workflow_dispatch:  # Только ручной запуск
  push:
    branches: [main]
    paths:
      - 'content/posts/**'
      - 'assets/images/posts/**'

jobs:
  fix-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Fix image references
      run: |
        python .github/scripts/fix_image_references.py

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add content/posts/*.md
        git diff --staged --quiet || git commit -m "🤖 Fix image references in articles"
        git push
