name: Generate Content Data

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Generate articles.json
        run: |
          python .github/scripts/generate_data.py

      - name: Commit and push generated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/articles.json
          git commit -m "Update articles data" || echo "No changes to commit"
          git push
