name: Generate AI Content

on:
  schedule:
    - cron: '0 0 * * 1'  # Каждый понедельник в 00:00 (раз в неделю)
  workflow_dispatch:       # Ручной запуск

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Create content directory
        run: mkdir -p content/posts

      - name: Debug - List files
        run: |
          echo "Текущая структура:"
          ls -la
          echo "Content directory:"
          ls -la content/ || echo "No content dir"
          echo "Posts directory:"
          ls -la content/posts/ || echo "No posts dir"

      - name: Generate blog post
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          echo "Запуск генерации поста..."
          python .github/scripts/generate_post.py
          echo "Генерация завершена"

      - name: Check generated files
        run: |
          echo "Проверяем созданные файлы:"
          ls -la content/posts/ || echo "Папка posts не существует"
          if [ -f "content/posts/test-article.md" ]; then
            echo "=== СОДЕРЖИМОЕ ФАЙЛА ==="
            cat content/posts/test-article.md
            echo "=== КОНЕЦ ФАЙЛА ==="
          else
            echo "Файл test-article.md не создан"
            ls -la content/ || true
            ls -la content/posts/ || true
          fi

      - name: Commit and push changes
        if: success() && contains(steps.check.outputs.files, 'content/posts/')
        run: |
          echo "Добавляем изменения в git..."
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add content/posts/*.md
          
          if git diff --staged --quiet; then
            echo "Нет изменений для коммита"
          else
            git commit -m "Auto-generated post: $(date +'%Y-%m-%d')"
            git push
            echo "Изменения запушены"
          fi

      - name: Show final structure
        run: |
          echo "Финальная структура:"
          find . -name "*.md" -type f | head -10
          echo "Content posts:"
          ls -la content/posts/ || echo "No posts directory"
