name: Setup Telegram Webhook

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'api/telegram.js'
      - '.github/workflows/setup-webhook.yml'

jobs:
  setup-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Telegram Webhook
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        VERCEL_URL: ${{ secrets.VERCEL_URL }}  # Добавьте этот секрет
      run: |
        echo "🔄 Настройка вебхука для Telegram бота..."
        
        # Установка вебхука
        response=$(curl -s -X POST \
          "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook" \
          -H "Content-Type: application/json" \
          -d "{\"url\": \"$VERCEL_URL/api/telegram\", \"max_connections\": 100}")
        
        echo "📋 Ответ от Telegram API:"
        echo $response | jq .
        
        # Проверка статуса вебхука
        echo "🔍 Проверка статуса вебхука..."
        curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/getWebhookInfo" | jq .
