name: 🧪 Simple File Test

on:
  workflow_dispatch:

jobs:
  test-file-creation:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 📁 Create directory structure
        run: |
          echo "Создаем папки..."
          mkdir -p content/posts
          echo "Текущая структура:"
          pwd
          ls -la
          ls -la content/ || echo "No content dir"
          
      - name: 📝 Create test file
        run: |
          echo "Создаем тестовый файл..."
          echo "---" > content/posts/test-file.md
          echo "title: 'Тестовый файл'" >> content/posts/test-file.md
          echo "date: 2024-01-20T10:00:00+03:00" >> content/posts/test-file.md
          echo "draft: false" >> content/posts/test-file.md
          echo "---" >> content/posts/test-file.md
          echo "" >> content/posts/test-file.md
          echo "# Это тестовый файл" >> content/posts/test-file.md
          echo "" >> content/posts/test-file.md
          echo "Создано: $(date)" >> content/posts/test-file.md
          
          echo "Файл создан! Проверяем:"
          ls -la content/posts/
          cat content/posts/test-file.md
          
      - name: 💾 Commit and push
        run: |
          echo "Коммитим изменения..."
          git config --global user.email "test@example.com"
          git config --global user.name "Test Bot"
          
          git add content/posts/test-file.md
          git status
          
          if ! git diff --staged --quiet; then
            git commit -m "Добавлен тестовый файл"
            git push
            echo "✅ Файл успешно добавлен и запушен!"
          else
            echo "❌ Нет изменений для коммита"
            echo "Проверяем существующие файлы:"
            find . -name "*.md" -type f
          fi
