name: 🧪 Simple File Test

on:
  workflow_dispatch:

permissions:
  contents: write  # ← ДАЕМ ПРАВА НА ЗАПИСЬ!

jobs:
  test-file-creation:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 📁 Create directory structure
        run: |
          echo "Создаем папки..."
          mkdir -p content/posts
          echo "Текущая структура:"
          pwd
          ls -la
          ls -la content/ || echo "No content dir"
          
      - name: 📝 Create test file
        run: |
          echo "Создаем тестовый файл..."
          cat > content/posts/test-file.md << EOF
---
title: "Тестовый файл"
date: 2024-01-20T10:00:00+03:00
draft: false
---

# Это тестовый файл

Создано: $(date)
EOF
          
          echo "Файл создан! Проверяем:"
          ls -la content/posts/
          cat content/posts/test-file.md
          
      - name: 💾 Commit and push
        run: |
          echo "Коммитим изменения..."
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git add content/posts/test-file.md
          git status
          
          if ! git diff --staged --quiet; then
            git commit -m "Добавлен тестовый файл"
            git push
            echo "✅ Файл успешно добавлен и запушен!"
          else
            echo "❌ Нет изменений для коммита"
          fi
